[package]
name = "wirt-cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "wirt"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
cap-fs-ext = "=4.0.2"
cap-std = "=4.0.2"
serde_json.workspace = true
wirt = { path = "../wirt" }

[dev-dependencies]
tempfile.workspace = true
