[package]
name = "wirt-sdk"
version = "0.2.0"
edition = "2021"

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "1", features = ["alloc"], default-features = false }
wit-bindgen = "0.39"

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
