[package]
name = "gstreamer-preview"
version = "0.3.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wirt-sdk = { git = "https://codeberg.org/0xdev/wirt.git", rev = "1fc2a8edcbb17830a6c6f46604453ca9126dc387", version = "0.3.0" }
serde = { version = "1", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "1", features = ["alloc"], default-features = false }

[workspace]

[profile.release]
opt-level = "z"         # Optimize for size
lto = true              # Link-time optimization
strip = true            # Strip debug symbols
panic = "abort"         # Smaller panic handler
codegen-units = 1       # Better optimization (slower compile, smaller binary)
