[package]
name = "malicious-metadata"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wirt-sdk = { git = "https://codeberg.org/0xdev/wirt.git", rev = "1fc2a8edcbb17830a6c6f46604453ca9126dc387", version = "0.3.0" }

[workspace]

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
