[package]
name = "arclain_plugins"
version = "0.1.0"
edition = "2021"

[dependencies]
arclain_core = { path = "../core" }
arclain_db = { path = "../db" }
arclain_data = { path = "../data" }
wasmtime = { version = "26.0.0", features = ["component-model"] }
wasmtime-wasi = "26.0.0"
anyhow = "1"
thiserror = "2.0"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tracing = "0.1"
toml = "0.9.8"
parking_lot = "0.12"
dirs = "6.0.0"
reqwest = { version = "0.12", features = ["blocking", "json"] }
tokio = { version = "1", features = ["rt", "sync"] }
rfd = "0.16.0"
arclain-http = { path = "../http" }

[dev-dependencies]
tempfile = "3"
mockito = "1.5"
