//! Keyboard key enum + bidirectional egui mapping.
//!
//! Lifted out of `types.rs` so the hotkey domain types stay focused on
//! action/binding/modifier shape; the 270-line key dictionary lives
//! here on its own.

use serde::{Deserialize, Serialize};

/// Keyboard keys that can be bound to hotkeys
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum KeyboardKey {
    // Letters
    A,
    B,
    C,
    D,
    E,
    F,
    G,
    H,
    I,
    J,
    K,
    L,
    M,
    N,
    O,
    P,
    Q,
    R,
    S,
    T,
    U,
    V,
    W,
    X,
    Y,
    Z,
    // Numbers
    Num0,
    Num1,
    Num2,
    Num3,
    Num4,
    Num5,
    Num6,
    Num7,
    Num8,
    Num9,
    // Function keys
    F1,
    F2,
    F3,
    F4,
    F5,
    F6,
    F7,
    F8,
    F9,
    F10,
    F11,
    F12,
    // Navigation
    Left,
    Right,
    Up,
    Down,
    Home,
    End,
    PageUp,
    PageDown,
    // Special
    Backspace,
    Delete,
    Enter,
    Escape,
    Tab,
    Space,
    Comma,
}

impl KeyboardKey {
    pub fn display_name(&self) -> &'static str {
        match self {
            KeyboardKey::A => "A",
            KeyboardKey::B => "B",
            KeyboardKey::C => "C",
            KeyboardKey::D => "D",
            KeyboardKey::E => "E",
            KeyboardKey::F => "F",
            KeyboardKey::G => "G",
            KeyboardKey::H => "H",
            KeyboardKey::I => "I",
            KeyboardKey::J => "J",
            KeyboardKey::K => "K",
            KeyboardKey::L => "L",
            KeyboardKey::M => "M",
            KeyboardKey::N => "N",
            KeyboardKey::O => "O",
            KeyboardKey::P => "P",
            KeyboardKey::Q => "Q",
            KeyboardKey::R => "R",
            KeyboardKey::S => "S",
            KeyboardKey::T => "T",
            KeyboardKey::U => "U",
            KeyboardKey::V => "V",
            KeyboardKey::W => "W",
            KeyboardKey::X => "X",
            KeyboardKey::Y => "Y",
            KeyboardKey::Z => "Z",
            KeyboardKey::Num0 => "0",
            KeyboardKey::Num1 => "1",
            KeyboardKey::Num2 => "2",
            KeyboardKey::Num3 => "3",
            KeyboardKey::Num4 => "4",
            KeyboardKey::Num5 => "5",
            KeyboardKey::Num6 => "6",
            KeyboardKey::Num7 => "7",
            KeyboardKey::Num8 => "8",
            KeyboardKey::Num9 => "9",
            KeyboardKey::F1 => "F1",
            KeyboardKey::F2 => "F2",
            KeyboardKey::F3 => "F3",
            KeyboardKey::F4 => "F4",
            KeyboardKey::F5 => "F5",
            KeyboardKey::F6 => "F6",
            KeyboardKey::F7 => "F7",
            KeyboardKey::F8 => "F8",
            KeyboardKey::F9 => "F9",
            KeyboardKey::F10 => "F10",
            KeyboardKey::F11 => "F11",
            KeyboardKey::F12 => "F12",
            KeyboardKey::Left => "←",
            KeyboardKey::Right => "→",
            KeyboardKey::Up => "↑",
            KeyboardKey::Down => "↓",
            KeyboardKey::Home => "Home",
            KeyboardKey::End => "End",
            KeyboardKey::PageUp => "Page Up",
            KeyboardKey::PageDown => "Page Down",
            KeyboardKey::Backspace => "Backspace",
            KeyboardKey::Delete => "Delete",
            KeyboardKey::Enter => "Enter",
            KeyboardKey::Escape => "Esc",
            KeyboardKey::Tab => "Tab",
            KeyboardKey::Space => "Space",
            KeyboardKey::Comma => ",",
        }
    }

    /// Convert from egui Key
    pub fn from_egui(key: egui::Key) -> Option<Self> {
        Some(match key {
            egui::Key::A => KeyboardKey::A,
            egui::Key::B => KeyboardKey::B,
            egui::Key::C => KeyboardKey::C,
            egui::Key::D => KeyboardKey::D,
            egui::Key::E => KeyboardKey::E,
            egui::Key::F => KeyboardKey::F,
            egui::Key::G => KeyboardKey::G,
            egui::Key::H => KeyboardKey::H,
            egui::Key::I => KeyboardKey::I,
            egui::Key::J => KeyboardKey::J,
            egui::Key::K => KeyboardKey::K,
            egui::Key::L => KeyboardKey::L,
            egui::Key::M => KeyboardKey::M,
            egui::Key::N => KeyboardKey::N,
            egui::Key::O => KeyboardKey::O,
            egui::Key::P => KeyboardKey::P,
            egui::Key::Q => KeyboardKey::Q,
            egui::Key::R => KeyboardKey::R,
            egui::Key::S => KeyboardKey::S,
            egui::Key::T => KeyboardKey::T,
            egui::Key::U => KeyboardKey::U,
            egui::Key::V => KeyboardKey::V,
            egui::Key::W => KeyboardKey::W,
            egui::Key::X => KeyboardKey::X,
            egui::Key::Y => KeyboardKey::Y,
            egui::Key::Z => KeyboardKey::Z,
            egui::Key::Num0 => KeyboardKey::Num0,
            egui::Key::Num1 => KeyboardKey::Num1,
            egui::Key::Num2 => KeyboardKey::Num2,
            egui::Key::Num3 => KeyboardKey::Num3,
            egui::Key::Num4 => KeyboardKey::Num4,
            egui::Key::Num5 => KeyboardKey::Num5,
            egui::Key::Num6 => KeyboardKey::Num6,
            egui::Key::Num7 => KeyboardKey::Num7,
            egui::Key::Num8 => KeyboardKey::Num8,
            egui::Key::Num9 => KeyboardKey::Num9,
            egui::Key::F1 => KeyboardKey::F1,
            egui::Key::F2 => KeyboardKey::F2,
            egui::Key::F3 => KeyboardKey::F3,
            egui::Key::F4 => KeyboardKey::F4,
            egui::Key::F5 => KeyboardKey::F5,
            egui::Key::F6 => KeyboardKey::F6,
            egui::Key::F7 => KeyboardKey::F7,
            egui::Key::F8 => KeyboardKey::F8,
            egui::Key::F9 => KeyboardKey::F9,
            egui::Key::F10 => KeyboardKey::F10,
            egui::Key::F11 => KeyboardKey::F11,
            egui::Key::F12 => KeyboardKey::F12,
            egui::Key::ArrowLeft => KeyboardKey::Left,
            egui::Key::ArrowRight => KeyboardKey::Right,
            egui::Key::ArrowUp => KeyboardKey::Up,
            egui::Key::ArrowDown => KeyboardKey::Down,
            egui::Key::Home => KeyboardKey::Home,
            egui::Key::End => KeyboardKey::End,
            egui::Key::PageUp => KeyboardKey::PageUp,
            egui::Key::PageDown => KeyboardKey::PageDown,
            egui::Key::Backspace => KeyboardKey::Backspace,
            egui::Key::Delete => KeyboardKey::Delete,
            egui::Key::Enter => KeyboardKey::Enter,
            egui::Key::Escape => KeyboardKey::Escape,
            egui::Key::Tab => KeyboardKey::Tab,
            egui::Key::Space => KeyboardKey::Space,
            _ => return None,
        })
    }

    /// Convert to egui Key
    pub fn to_egui(&self) -> egui::Key {
        match self {
            KeyboardKey::A => egui::Key::A,
            KeyboardKey::B => egui::Key::B,
            KeyboardKey::C => egui::Key::C,
            KeyboardKey::D => egui::Key::D,
            KeyboardKey::E => egui::Key::E,
            KeyboardKey::F => egui::Key::F,
            KeyboardKey::G => egui::Key::G,
            KeyboardKey::H => egui::Key::H,
            KeyboardKey::I => egui::Key::I,
            KeyboardKey::J => egui::Key::J,
            KeyboardKey::K => egui::Key::K,
            KeyboardKey::L => egui::Key::L,
            KeyboardKey::M => egui::Key::M,
            KeyboardKey::N => egui::Key::N,
            KeyboardKey::O => egui::Key::O,
            KeyboardKey::P => egui::Key::P,
            KeyboardKey::Q => egui::Key::Q,
            KeyboardKey::R => egui::Key::R,
            KeyboardKey::S => egui::Key::S,
            KeyboardKey::T => egui::Key::T,
            KeyboardKey::U => egui::Key::U,
            KeyboardKey::V => egui::Key::V,
            KeyboardKey::W => egui::Key::W,
            KeyboardKey::X => egui::Key::X,
            KeyboardKey::Y => egui::Key::Y,
            KeyboardKey::Z => egui::Key::Z,
            KeyboardKey::Num0 => egui::Key::Num0,
            KeyboardKey::Num1 => egui::Key::Num1,
            KeyboardKey::Num2 => egui::Key::Num2,
            KeyboardKey::Num3 => egui::Key::Num3,
            KeyboardKey::Num4 => egui::Key::Num4,
            KeyboardKey::Num5 => egui::Key::Num5,
            KeyboardKey::Num6 => egui::Key::Num6,
            KeyboardKey::Num7 => egui::Key::Num7,
            KeyboardKey::Num8 => egui::Key::Num8,
            KeyboardKey::Num9 => egui::Key::Num9,
            KeyboardKey::F1 => egui::Key::F1,
            KeyboardKey::F2 => egui::Key::F2,
            KeyboardKey::F3 => egui::Key::F3,
            KeyboardKey::F4 => egui::Key::F4,
            KeyboardKey::F5 => egui::Key::F5,
            KeyboardKey::F6 => egui::Key::F6,
            KeyboardKey::F7 => egui::Key::F7,
            KeyboardKey::F8 => egui::Key::F8,
            KeyboardKey::F9 => egui::Key::F9,
            KeyboardKey::F10 => egui::Key::F10,
            KeyboardKey::F11 => egui::Key::F11,
            KeyboardKey::F12 => egui::Key::F12,
            KeyboardKey::Left => egui::Key::ArrowLeft,
            KeyboardKey::Right => egui::Key::ArrowRight,
            KeyboardKey::Up => egui::Key::ArrowUp,
            KeyboardKey::Down => egui::Key::ArrowDown,
            KeyboardKey::Home => egui::Key::Home,
            KeyboardKey::End => egui::Key::End,
            KeyboardKey::PageUp => egui::Key::PageUp,
            KeyboardKey::PageDown => egui::Key::PageDown,
            KeyboardKey::Backspace => egui::Key::Backspace,
            KeyboardKey::Delete => egui::Key::Delete,
            KeyboardKey::Enter => egui::Key::Enter,
            KeyboardKey::Escape => egui::Key::Escape,
            KeyboardKey::Tab => egui::Key::Tab,
            KeyboardKey::Space => egui::Key::Space,
            KeyboardKey::Comma => egui::Key::Comma,
        }
    }
}
