[package]
name = "ui-demo"
version = "0.2.1"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
wirt-sdk = { git = "https://codeberg.org/0xdev/wirt.git", rev = "1fc2a8edcbb17830a6c6f46604453ca9126dc387", version = "0.3.0" }
serde = { version = "1", features = ["derive", "alloc"], default-features = false }
serde_json = { version = "1", features = ["alloc"], default-features = false }

[package.metadata.workspaces]
independent = true

[workspace]

[profile.release]
opt-level = "z"
lto = true
strip = true
panic = "abort"
codegen-units = 1
