//! WASM runtime wrapper using wasmtime component model
//!
//! This module provides the WASM runtime with full host function support.

use crate::host_functions::HostFunctions;
use crate::types::{
    PluginCapability, PluginError, PluginEvent, PluginExtensionPoint, PluginMetadata,
    PluginResponse, PluginUiElement, Result,
};
use crate::PluginWorld; // Generated by bindgen!
use arclain_core::sevenzip::SevenZipCli;
use std::path::Path;
use std::sync::Arc;
use tracing::{debug, error, info};
use wasmtime::component::{Component, Linker};
use wasmtime::{Config, Engine, Store};

/// WASM runtime for executing plugins
pub struct WasmRuntime {
    engine: Engine,
}

impl WasmRuntime {
    /// Create a new WASM runtime
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true); // Enable component model

        let engine = Engine::new(&config).map_err(|e| PluginError::WasmError(e.to_string()))?;

        info!("WASM runtime initialized (Component Model enabled)");
        Ok(Self { engine })
    }

    /// Load a WASM component from a file
    pub fn load_module(&self, path: &Path) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from: {}", path.display());

        let component = Component::from_file(&self.engine, path)
            .map_err(|e| PluginError::LoadError(format!("Failed to load component: {}", e)))?;

        info!("WASM component loaded successfully: {}", path.display());

        Ok(LoadedPlugin {
            component,
            engine: self.engine.clone(),
            _path: path.to_path_buf(),
        })
    }

    /// Load a WASM component from bytes
    pub fn load_module_from_bytes(&self, bytes: &[u8]) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from bytes ({} bytes)", bytes.len());

        let component = Component::from_binary(&self.engine, bytes)
            .map_err(|e| PluginError::LoadError(e.to_string()))?;

        info!("WASM component loaded successfully from bytes");

        Ok(LoadedPlugin {
            component,
            engine: self.engine.clone(),
            _path: std::path::PathBuf::from("<bytes>"),
        })
    }
}

/// A loaded WASM plugin ready for execution
pub struct LoadedPlugin {
    component: Component,
    engine: Engine,
    _path: std::path::PathBuf,
}

impl LoadedPlugin {
    pub fn instantiate(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
    ) -> Result<PluginInstance> {
        self.instantiate_with_backend(capabilities, requests_per_minute, None)
    }

    pub fn instantiate_with_backend(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
        backend: Option<Arc<SevenZipCli>>,
    ) -> Result<PluginInstance> {
        // Create host functions state
        let host_funcs = if let Some(backend) = backend {
            HostFunctions::with_backend(
                capabilities.into_iter().collect(),
                requests_per_minute,
                backend,
            )
        } else {
            HostFunctions::new(capabilities.into_iter().collect(), requests_per_minute)
        };

        let mut store = Store::new(&self.engine, host_funcs);
        let mut linker = Linker::new(&self.engine);

        // Link WASI functions
        wasmtime_wasi::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Link host functions
        crate::PluginWorld::add_to_linker(&mut linker, |state: &mut HostFunctions| state)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Instantiate the component
        let plugin = PluginWorld::instantiate(&mut store, &self.component, &linker)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        debug!("Plugin instance created");

        Ok(PluginInstance {
            store,
            plugin,
            metadata: None,
        })
    }
}

/// An instantiated plugin that can receive events
pub struct PluginInstance {
    store: Store<HostFunctions>,
    plugin: PluginWorld,
    metadata: Option<PluginMetadata>,
}

impl PluginInstance {
    /// Initialize the plugin
    pub fn init(&mut self) -> Result<()> {
        self.plugin
            .call_init(&mut self.store)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        debug!("Plugin initialized successfully");
        Ok(())
    }

    /// Get plugin metadata
    pub fn get_metadata(&mut self) -> Result<PluginMetadata> {
        if let Some(metadata) = &self.metadata {
            return Ok(metadata.clone());
        }

        // TODO: Add metadata to WIT interface
        // For now, return default
        Ok(PluginMetadata {
            id: "unknown".to_string(),
            name: "Unknown Plugin".to_string(),
            version: "0.0.0".to_string(),
            description: "Metadata not yet implemented in WIT".to_string(),
            author: "Unknown".to_string(),
        })
    }

    /// Dispatch an event to the plugin
    pub fn on_event(&mut self, _event: &PluginEvent) -> Result<PluginResponse> {
        Ok(PluginResponse::None)
    }

    /// Get UI layout for a specific extension point
    pub fn get_ui_layout(
        &mut self,
        extension_point: PluginExtensionPoint,
    ) -> Result<Vec<PluginUiElement>> {
        let ep_str = match extension_point {
            PluginExtensionPoint::MainPage => "MainPage",
            PluginExtensionPoint::Sidebar => "Sidebar",
            PluginExtensionPoint::ContextMenu => "ContextMenu",
        };

        let ui_elements = self
            .plugin
            .call_get_ui_layout(&mut self.store, ep_str)
            .map_err(|e| PluginError::ExecutionError(e.to_string()))?;

        let converted: Vec<PluginUiElement> = ui_elements
            .into_iter()
            .map(|e| convert_ui_element(e))
            .collect();

        Ok(converted)
    }

    /// Send a UI event to the plugin
    pub fn send_ui_event(&mut self, element_id: &str, value: Option<String>) -> Result<bool> {
        info!(
            "PluginInstance::send_ui_event: Calling plugin handler for {}",
            element_id
        );

        self.plugin
            .call_on_ui_event(&mut self.store, element_id, value.as_deref())
            .map_err(|e| {
                error!(
                    "PluginInstance::send_ui_event: Failed to call plugin: {}",
                    e
                );
                PluginError::ExecutionError(e.to_string())
            })?;

        info!("PluginInstance::send_ui_event: Plugin handler returned successfully");
        Ok(true)
    }

    /// Clean up the plugin
    pub fn cleanup(&mut self) -> Result<()> {
        // Cleanup is handled by Drop in Component Model usually,
        // or we can add a specific cleanup function to WIT
        Ok(())
    }

    /// Get pending messages from the plugin
    pub fn get_pending_messages(&self) -> Vec<(String, String)> {
        let data = self.store.data();
        let mut messages = data.pending_messages.lock();
        let pending = messages.clone();
        messages.clear();
        pending
    }

    /// Get emitted metadata from the plugin
    pub fn get_emitted_metadata(&self) -> Option<String> {
        let data = self.store.data();
        let mut metadata = data.emitted_metadata.lock();
        metadata.take()
    }

    /// Set the current archive context for the plugin
    pub fn set_archive_context(&mut self, archive_path: Option<String>, password: Option<String>) {
        self.store
            .data()
            .set_archive_context(archive_path, password);
    }
}

fn convert_ui_element(element: crate::arclain::plugin::ui::UiElement) -> PluginUiElement {
    use crate::arclain::plugin::ui::UiElement;
    use crate::types::PluginUiElement as InternalElement;

    match element {
        UiElement::Label(config) => InternalElement::Label {
            text: config.text,
            bold: config.bold,
            size: config.size,
        },
        UiElement::Button(config) => InternalElement::Button {
            id: config.id,
            label: config.label,
        },
        UiElement::TextInput(config) => InternalElement::TextInput {
            id: config.id,
            label: config.label,
            value: config.value,
        },
        UiElement::Checkbox(config) => InternalElement::Checkbox {
            id: config.id,
            label: config.label,
            checked: config.checked,
        },
        UiElement::RadioGroup(config) => InternalElement::RadioGroup {
            id: config.id,
            label: config.label,
            options: config.options,
            selected: config.selected,
        },
        UiElement::Slider(config) => InternalElement::Slider {
            id: config.id,
            label: config.label,
            value: config.value,
            min: config.min,
            max: config.max,
            step: config.step,
        },
        UiElement::Dropdown(config) => InternalElement::Dropdown {
            id: config.id,
            label: config.label,
            options: config.options,
            selected: config.selected,
        },
        UiElement::Separator => InternalElement::Separator,
        UiElement::Space(size) => InternalElement::Space { size },
    }
}
