//! WASM runtime wrapper using wasmtime component model
//!
//! This module provides the WASM runtime with full host function support.

use crate::host_functions::HostFunctions;
use crate::types::{
    PluginCapability, PluginError, PluginEvent, PluginExtensionPoint, PluginMetadata,
    PluginResponse, PluginUiElement, Result,
};
use crate::PluginWorld; // Generated by bindgen!

use arclain_core::ArchiveBackend;
use std::path::Path;
use std::sync::Arc;
use tracing::{debug, error, info};
use wasmtime::component::{Component, Linker};
use wasmtime::{Config, Engine, Store};

/// WASM runtime for executing plugins
pub struct WasmRuntime {
    engine: Engine,
}

impl WasmRuntime {
    /// Create a new WASM runtime
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true); // Enable component model

        let engine = Engine::new(&config).map_err(|e| PluginError::WasmError(e.to_string()))?;

        info!("WASM runtime initialized (Component Model enabled)");
        Ok(Self { engine })
    }

    /// Load a WASM component from a file
    pub fn load_module(&self, id: String, path: &Path) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from: {}", path.display());

        let component = Component::from_file(&self.engine, path)
            .map_err(|e| PluginError::LoadError(format!("Failed to load component: {}", e)))?;

        info!("WASM component loaded successfully: {}", path.display());

        Ok(LoadedPlugin {
            id,
            component,
            engine: self.engine.clone(),
            _path: path.to_path_buf(),
        })
    }

    /// Load a WASM component from bytes
    pub fn load_module_from_bytes(&self, id: String, bytes: &[u8]) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from bytes ({} bytes)", bytes.len());

        let component = Component::from_binary(&self.engine, bytes)
            .map_err(|e| PluginError::LoadError(e.to_string()))?;

        info!("WASM component loaded successfully from bytes");

        Ok(LoadedPlugin {
            id,
            component,
            engine: self.engine.clone(),
            _path: std::path::PathBuf::from("<bytes>"),
        })
    }
}

/// A loaded WASM plugin ready for execution
pub struct LoadedPlugin {
    pub id: String,
    component: Component,
    engine: Engine,
    _path: std::path::PathBuf,
}

impl LoadedPlugin {
    pub fn instantiate(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
        settings: std::collections::HashMap<String, String>,
    ) -> Result<PluginInstance> {
        self.instantiate_with_backend(capabilities, requests_per_minute, None, None, settings)
    }

    pub fn instantiate_with_backend(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
        backend: Option<Arc<dyn ArchiveBackend>>,
        metadata_store: Option<Arc<arclain_db::MetadataStore>>,
        settings: std::collections::HashMap<String, String>,
    ) -> Result<PluginInstance> {
        // Create host functions state
        let mut host_funcs = if let Some(backend) = backend {
            HostFunctions::with_backend(
                self.id.clone(),
                capabilities.into_iter().collect(),
                requests_per_minute,
                backend,
                settings,
            )
        } else {
            HostFunctions::new(
                self.id.clone(),
                capabilities.into_iter().collect(),
                requests_per_minute,
                settings,
            )
        };

        if let Some(store) = metadata_store {
            host_funcs.set_metadata_store(store);
        }

        let mut store = Store::new(&self.engine, host_funcs);
        let mut linker = Linker::new(&self.engine);

        // Link WASI functions
        wasmtime_wasi::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Link host functions
        crate::PluginWorld::add_to_linker(&mut linker, |state: &mut HostFunctions| state)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Instantiate the component
        let plugin = PluginWorld::instantiate(&mut store, &self.component, &linker)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        debug!("Plugin instance created");

        Ok(PluginInstance {
            store,
            plugin,
            metadata: None,
        })
    }
}

/// An instantiated plugin that can receive events
pub struct PluginInstance {
    store: Store<HostFunctions>,
    plugin: PluginWorld,
    metadata: Option<PluginMetadata>,
}

impl PluginInstance {
    /// Initialize the plugin
    pub fn init(&mut self) -> Result<()> {
        self.plugin
            .call_init(&mut self.store)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        debug!("Plugin initialized successfully");
        Ok(())
    }

    /// Get plugin metadata
    pub fn get_metadata(&mut self) -> Result<PluginMetadata> {
        if let Some(metadata) = &self.metadata {
            return Ok(metadata.clone());
        }

        // TODO: Add metadata to WIT interface
        // For now, return default
        Ok(PluginMetadata {
            id: "unknown".to_string(),
            name: "Unknown Plugin".to_string(),
            version: "0.0.0".to_string(),
            description: "Metadata not yet implemented in WIT".to_string(),
            author: "Unknown".to_string(),
        })
    }

    /// Get default organization rules from the plugin
    pub fn get_default_rules(
        &mut self,
    ) -> Result<Vec<crate::bindings::arclain::plugin::rules::PluginRuleDefinition>> {
        self.plugin
            .call_get_default_rules(&mut self.store)
            .map_err(|e| PluginError::ExecutionError(e.to_string()))
    }

    /// Dispatch an event to the plugin
    pub fn on_event(&mut self, _event: &PluginEvent) -> Result<PluginResponse> {
        Ok(PluginResponse::None)
    }

    /// Get UI layout for a specific extension point
    pub fn get_ui_layout(
        &mut self,
        extension_point: PluginExtensionPoint,
    ) -> Result<crate::types::PluginLayout> {
        let ep_str = match extension_point {
            PluginExtensionPoint::MainPage => "MainPage".to_string(),
            PluginExtensionPoint::Sidebar => "Sidebar".to_string(), // Keep Sidebar enum for now
            PluginExtensionPoint::ContextMenu => "ContextMenu".to_string(),
            PluginExtensionPoint::PluginButton => "PluginButton".to_string(),
            PluginExtensionPoint::Panel => "Panel".to_string(),
            PluginExtensionPoint::Settings => "Settings".to_string(),
            PluginExtensionPoint::Dialog(ref id) => format!("Dialog:{}", id),
            PluginExtensionPoint::Page(ref id) => format!("Page:{}", id),
        };

        let layout = self
            .plugin
            .call_get_ui_layout(&mut self.store, &ep_str)
            .map_err(|e| PluginError::ExecutionError(e.to_string()))?;

        let converted = convert_plugin_layout(layout);

        Ok(converted)
    }

    /// Send a UI event to the plugin and get actions back
    pub fn send_ui_event(
        &mut self,
        element_id: &str,
        value: Option<String>,
    ) -> Result<Vec<crate::types::PluginAction>> {
        info!(
            "PluginInstance::send_ui_event: Calling plugin handler for {}",
            element_id
        );

        let actions = self
            .plugin
            .call_on_ui_event(&mut self.store, element_id, value.as_deref())
            .map_err(|e| {
                error!(
                    "PluginInstance::send_ui_event: Failed to call plugin: {}",
                    e
                );
                PluginError::ExecutionError(e.to_string())
            })?;

        info!(
            "PluginInstance::send_ui_event: Plugin returned {} actions",
            actions.len()
        );

        Ok(actions.into_iter().map(convert_plugin_action).collect())
    }

    /// Clean up the plugin
    pub fn cleanup(&mut self) -> Result<()> {
        // Cleanup is handled by Drop in Component Model usually,
        // or we can add a specific cleanup function to WIT
        Ok(())
    }

    /// Get pending messages from the plugin
    pub fn get_pending_messages(&self) -> Vec<(String, String)> {
        let data = self.store.data();
        let mut messages = data.pending_messages.lock();
        let pending = messages.clone();
        messages.clear();
        pending
    }

    /// Get emitted metadata from the plugin
    pub fn get_emitted_metadata(&self) -> Option<String> {
        let data = self.store.data();
        let mut metadata = data.emitted_metadata.lock();
        metadata.take()
    }

    /// Set the content cache for host functions
    pub fn set_content_cache(&mut self, cache: Option<Arc<arclain_data::ContentCache>>) {
        let host = self.store.data_mut();
        match cache {
            Some(c) => host.set_content_cache(c),
            None => host.content_cache = None,
        }
    }

    /// Set the resource manager for host functions
    pub fn set_resource_manager(&mut self, manager: Option<Arc<arclain_data::ResourceManager>>) {
        let host = self.store.data_mut();
        match manager {
            Some(m) => host.set_resource_manager(m),
            None => host.resource_manager = None,
        }
    }

    /// Set the async HTTP client for host functions
    pub fn set_async_http_client(&mut self, client: Option<Arc<arclain_http::AsyncHttpClient>>) {
        let host = self.store.data_mut();
        match client {
            Some(c) => host.set_async_http_client(c),
            None => host.async_http_client = None,
        }
    }

    /// Set archive context
    pub fn set_archive_context(&mut self, archive_path: Option<String>, password: Option<String>) {
        self.store
            .data_mut()
            .set_archive_context(archive_path, password);
    }

    /// Set the metadata store for host functions
    pub fn set_metadata_store(&mut self, store: Option<Arc<arclain_db::MetadataStore>>) {
        let host = self.store.data_mut();
        match store {
            Some(c) => host.set_metadata_store(c),
            None => host.metadata_store = None,
        }
    }

    /// Set the cache database for host functions (new ProductMetadata table)
    pub fn set_cache_db(&mut self, db: Option<Arc<arclain_db::SqliteDb>>) {
        let host = self.store.data_mut();
        match db {
            Some(d) => host.set_cache_db(d),
            None => host.cache_db = None,
        }
    }

    /// Get network logs from the plugin
    pub fn get_network_log(&self) -> Vec<(std::time::SystemTime, String)> {
        let data = self.store.data();
        let logs = data.network_log.lock();
        logs.clone()
    }

    /// Get current settings from the plugin
    pub fn get_settings(&self) -> Option<std::collections::HashMap<String, String>> {
        let data = self.store.data();
        let settings = data.settings.lock();
        Some(settings.clone())
    }

    /// Get top-level tabs registered by this plugin
    pub fn get_top_tabs(&mut self) -> Result<Vec<crate::types::TopTabConfig>> {
        let tabs = self
            .plugin
            .call_get_top_tabs(&mut self.store)
            .map_err(|e| PluginError::ExecutionError(e.to_string()))?;

        Ok(tabs.into_iter().map(convert_top_tab_config).collect())
    }
}

fn convert_plugin_layout(
    layout: crate::arclain::plugin::ui::PluginLayout,
) -> crate::types::PluginLayout {
    use crate::arclain::plugin::ui::PluginLayout as WitLayout;
    use crate::types::PluginLayout as InternalLayout;

    match layout {
        WitLayout::Single(elements) => InternalLayout::Single {
            elements: elements.into_iter().map(convert_ui_element).collect(),
        },
        WitLayout::Split(config) => InternalLayout::Split {
            sidebar: config.sidebar.into_iter().map(convert_ui_element).collect(),
            content: config.content.into_iter().map(convert_ui_element).collect(),
            sidebar_width: config.sidebar_width,
        },
    }
}

fn convert_top_tab_config(
    config: crate::arclain::plugin::ui::TopTabConfig,
) -> crate::types::TopTabConfig {
    crate::types::TopTabConfig {
        id: config.id,
        label: config.label,
        icon: config.icon,
        badge: config.badge.map(|b| crate::types::BadgeConfig {
            count: b.count,
            dot: b.dot,
            color: b.color,
        }),
        priority: config.priority,
    }
}

fn convert_ui_element(element: crate::arclain::plugin::ui::UiElement) -> PluginUiElement {
    use crate::arclain::plugin::ui::UiElement;
    use crate::types::PluginUiElement as InternalElement;

    match element {
        UiElement::Label(config) => InternalElement::Label {
            text: config.text,
            bold: config.bold,
            size: config.size,
        },
        UiElement::Button(config) => {
            let action = config.action.map(|a| convert_button_action(a));
            InternalElement::Button {
                id: config.id,
                label: config.label,
                action,
            }
        }
        UiElement::TextInput(config) => InternalElement::TextInput {
            id: config.id,
            label: config.label,
            value: config.value,
        },
        UiElement::Checkbox(config) => InternalElement::Checkbox {
            id: config.id,
            label: config.label,
            checked: config.checked,
        },
        UiElement::RadioGroup(config) => InternalElement::RadioGroup {
            id: config.id,
            label: config.label,
            options: config.options,
            selected: config.selected,
        },
        UiElement::Slider(config) => InternalElement::Slider {
            id: config.id,
            label: config.label,
            value: config.value,
            min: config.min,
            max: config.max,
            step: config.step,
        },
        UiElement::Dropdown(config) => InternalElement::Dropdown {
            id: config.id,
            label: config.label,
            options: config.options,
            selected: config.selected,
        },
        UiElement::Separator => InternalElement::Separator,
        UiElement::Space(size) => InternalElement::Space { size },
        UiElement::Image(config) => InternalElement::Image {
            cache_key: config.cache_key,
            url: config.url,
            max_height: config.max_height,
        },
        UiElement::Tabs(config) => InternalElement::Tabs {
            id: config.id,
            tabs: config.tabs,
            selected: config.selected,
        },
        UiElement::ListContainer(config) => InternalElement::ListContainer {
            id: config.id,
            items: config
                .items
                .into_iter()
                .map(|item| InternalElement::ListItem {
                    id: item.id,
                    title: item.title,
                    subtitle: item.subtitle,
                    badge: item.badge,
                    image_key: item.image_key,
                    selected: item.selected,
                })
                .collect(),
            max_height: config.max_height,
            empty_message: config.empty_message,
        },
        UiElement::Loading(config) => InternalElement::Loading {
            message: config.message,
        },
    }
}

fn convert_button_action(
    action: crate::arclain::plugin::ui::ButtonAction,
) -> crate::types::ButtonAction {
    use crate::arclain::plugin::ui::ButtonAction as WitAction;
    use crate::types::ButtonAction as InternalAction;

    match action {
        WitAction::None => InternalAction::None,
        WitAction::ShowDialog(id) => InternalAction::ShowDialog { id },
        WitAction::CloseDialog => InternalAction::CloseDialog,
        WitAction::OpenPage(id) => InternalAction::OpenPage { id },
        WitAction::ClosePage => InternalAction::ClosePage,
        WitAction::Custom(s) => InternalAction::Custom(s),
    }
}

fn convert_plugin_action(
    action: crate::arclain::plugin::ui::PluginAction,
) -> crate::types::PluginAction {
    use crate::arclain::plugin::ui::PluginAction as WitAction;
    use crate::types::{PluginAction as InternalAction, ToastLevel};

    match action {
        WitAction::None => InternalAction::None,
        WitAction::EmitMetadata(json) => InternalAction::EmitMetadata { json },
        WitAction::CacheContent(req) => InternalAction::CacheContent {
            key: req.key,
            url: req.url,
        },
        WitAction::ShowToast(config) => InternalAction::ShowToast {
            message: config.message,
            level: match config.level {
                crate::arclain::plugin::ui::ToastLevel::Info => ToastLevel::Info,
                crate::arclain::plugin::ui::ToastLevel::Success => ToastLevel::Success,
                crate::arclain::plugin::ui::ToastLevel::Warning => ToastLevel::Warning,
                crate::arclain::plugin::ui::ToastLevel::Error => ToastLevel::Error,
            },
        },
        WitAction::ShowMessage(config) => InternalAction::ShowMessage {
            title: config.title,
            message: config.message,
        },
        WitAction::RefreshPanel(ep) => InternalAction::RefreshPanel {
            extension_point: ep,
        },
        WitAction::UpdateElement(update) => InternalAction::UpdateElement {
            id: update.id,
            value: update.value,
        },
    }
}
