//! WASM runtime wrapper using wasmtime component model
//!
//! This module provides the WASM runtime with full host function support.

use crate::conversions::{convert_plugin_action, convert_plugin_layout, convert_top_tab_config};
use crate::host_functions::HostFunctions;
use crate::types::{PluginCapability, PluginError, PluginExtensionPoint, PluginMetadata, Result};
use crate::PluginWorld; // Generated by bindgen!

use serde::Serialize;
use std::collections::HashMap;
use std::path::Path;
use std::sync::Arc;
use std::time::Duration;
use tracing::{debug, error, info};
use wasmtime::component::{Component, HasSelf, Linker};
use wasmtime::{Config, Engine, Store};

const FUEL_PER_EXPORT: u64 = 10_000_000;
const EPOCH_TICKS_PER_EXPORT: u64 = 10;
const EPOCH_TICK_INTERVAL: Duration = Duration::from_millis(10);
const MAX_UI_ELEMENTS: usize = 10_000;
const MAX_ACTIONS: usize = 1_024;
const MAX_SERIALIZED_RESULT_BYTES: usize = 1024 * 1024;
// Measured from the largest host-side representations permitted by the current
// WIT result shapes: layout 2,568,576 bytes, top tabs 3,256,216 bytes, rules
// 2,535,880 bytes, and actions 1,155,072 bytes. Eight MiB leaves more than 2x
// headroom without retaining Wasmtime's unsafe 128 MiB default.
const HOSTCALL_FUEL_BYTES: usize = 8 * 1024 * 1024;
// Wasmtime 47.0.1 keeps this error type private, so classification is pinned to
// the exact static root-cause text from component/func/options.rs.
const WASMTIME_47_HOSTCALL_FUEL_EXHAUSTED: &str =
    "too much data is being copied between the host and the guest: fuel allocated for hostcalls has been exhausted";
// Wasmtime's ResourceLimiter count errors are likewise private. Keep these
// locked-version strings exact so unrelated guest errors cannot be mistaken for
// terminal quota failures or leak engine details through PluginError.
const WASMTIME_47_INSTANCE_COUNT_EXCEEDED: &str =
    "resource limit exceeded: instance count too high at 33";
const WASMTIME_47_MEMORY_COUNT_EXCEEDED: &str =
    "resource limit exceeded: memory count too high at 5";
const WASMTIME_47_TABLE_COUNT_EXCEEDED: &str = "resource limit exceeded: table count too high at 9";

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
enum QuotaViolation {
    Result,
}

impl QuotaViolation {
    fn redacted_reason(self) -> &'static str {
        match self {
            Self::Result => "plugin result quota exceeded",
        }
    }
}

#[derive(Debug)]
enum ResultValidationError {
    Quota(QuotaViolation),
    Serialization(serde_json::Error),
}

#[derive(Default)]
struct ResultSizeWriter {
    bytes_written: usize,
    exceeded: bool,
}

impl std::io::Write for ResultSizeWriter {
    fn write(&mut self, buffer: &[u8]) -> std::io::Result<usize> {
        if self.bytes_written.saturating_add(buffer.len()) > MAX_SERIALIZED_RESULT_BYTES {
            self.exceeded = true;
            return Err(std::io::Error::other("plugin result quota exceeded"));
        }
        self.bytes_written += buffer.len();
        Ok(buffer.len())
    }

    fn flush(&mut self) -> std::io::Result<()> {
        Ok(())
    }
}

fn validate_serialized_result<T: Serialize + ?Sized>(
    value: &T,
) -> std::result::Result<(), ResultValidationError> {
    let mut writer = ResultSizeWriter::default();
    if let Err(error) = serde_json::to_writer(&mut writer, value) {
        return if writer.exceeded {
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        } else {
            Err(ResultValidationError::Serialization(error))
        };
    }
    Ok(())
}

fn validate_layout_result(
    layout: &crate::types::PluginLayout,
) -> std::result::Result<(), ResultValidationError> {
    fn charge_work(
        total: &mut usize,
        additional: usize,
        limit: usize,
    ) -> std::result::Result<(), ResultValidationError> {
        *total = total
            .checked_add(additional)
            .ok_or(ResultValidationError::Quota(QuotaViolation::Result))?;
        if *total > limit {
            return Err(ResultValidationError::Quota(QuotaViolation::Result));
        }
        Ok(())
    }

    fn charge_elements(
        roots: &[crate::types::PluginUiElement],
        work: &mut usize,
    ) -> std::result::Result<(), ResultValidationError> {
        use crate::types::PluginUiElement;

        let mut stack = vec![roots.iter()];
        while let Some(element) = stack.last_mut().and_then(Iterator::next) {
            charge_work(work, 1, MAX_UI_ELEMENTS)?;
            match element {
                PluginUiElement::RadioGroup { options, .. }
                | PluginUiElement::Dropdown { options, .. } => {
                    charge_work(work, options.len(), MAX_UI_ELEMENTS)?;
                }
                PluginUiElement::Tabs { tabs, .. } => {
                    charge_work(work, tabs.len(), MAX_UI_ELEMENTS)?;
                }
                PluginUiElement::ListContainer { items, .. } => stack.push(items.iter()),
                PluginUiElement::TagChips { tags, max_display } => {
                    let display_limit = max_display
                        .map(|limit| usize::try_from(limit).unwrap_or(usize::MAX))
                        .unwrap_or(tags.len());
                    let visible = display_limit.min(tags.len());
                    let overflow_label = usize::from(visible < tags.len());
                    charge_work(work, visible, MAX_UI_ELEMENTS)?;
                    charge_work(work, overflow_label, MAX_UI_ELEMENTS)?;
                }
                PluginUiElement::Toolbar { buttons } => {
                    charge_work(work, buttons.len(), MAX_UI_ELEMENTS)?;
                }
                PluginUiElement::Carousel { images, .. } => {
                    charge_work(work, images.len(), MAX_UI_ELEMENTS)?;
                }
                PluginUiElement::KeyValueList { items, .. }
                | PluginUiElement::MetadataGrid { items, .. } => {
                    charge_work(work, items.len(), MAX_UI_ELEMENTS)?;
                }
                _ => {}
            }

            while stack.last().is_some_and(|elements| elements.len() == 0) {
                stack.pop();
            }
        }
        Ok(())
    }

    let mut work = 0usize;
    match layout {
        crate::types::PluginLayout::Single { elements } => {
            charge_elements(elements, &mut work)?;
        }
        crate::types::PluginLayout::Split {
            sidebar, content, ..
        } => {
            charge_elements(sidebar, &mut work)?;
            charge_elements(content, &mut work)?;
        }
    }

    validate_serialized_result(layout)
}

fn validate_actions_result(
    actions: &[crate::types::PluginAction],
) -> std::result::Result<(), ResultValidationError> {
    let mut work = 0usize;
    for action in actions {
        work = work
            .checked_add(1)
            .ok_or(ResultValidationError::Quota(QuotaViolation::Result))?;
        if let crate::types::PluginAction::OpenLightbox { images, .. } = action {
            work = work
                .checked_add(images.len())
                .ok_or(ResultValidationError::Quota(QuotaViolation::Result))?;
        }
        if work > MAX_ACTIONS {
            return Err(ResultValidationError::Quota(QuotaViolation::Result));
        }
    }
    validate_serialized_result(actions)
}

#[derive(Debug, Default)]
struct InstanceAvailability {
    reason: Option<&'static str>,
}

impl InstanceAvailability {
    fn ensure_available(&self) -> Result<()> {
        match self.reason {
            Some(reason) => Err(PluginError::Unavailable(reason.to_string())),
            None => Ok(()),
        }
    }

    fn mark_unavailable<T>(&mut self, reason: &'static str) -> Result<T> {
        self.reason = Some(reason);
        Err(PluginError::Unavailable(reason.to_string()))
    }

    fn reason(&self) -> Option<&'static str> {
        self.reason
    }
}

fn resource_quota_reason(error: &wasmtime::Error) -> Option<&'static str> {
    if let Some(trap) = error.downcast_ref::<wasmtime::Trap>() {
        return match trap {
            wasmtime::Trap::OutOfFuel => Some("plugin fuel quota exceeded"),
            wasmtime::Trap::Interrupt => Some("plugin execution deadline exceeded"),
            _ => None,
        };
    }

    match error.root_cause().to_string().as_str() {
        WASMTIME_47_HOSTCALL_FUEL_EXHAUSTED => {
            return Some("plugin hostcall data quota exceeded");
        }
        WASMTIME_47_INSTANCE_COUNT_EXCEEDED => {
            return Some("plugin instance quota exceeded");
        }
        WASMTIME_47_MEMORY_COUNT_EXCEEDED => {
            return Some("plugin memory quota exceeded");
        }
        WASMTIME_47_TABLE_COUNT_EXCEEDED => {
            return Some("plugin table quota exceeded");
        }
        _ => {}
    }

    error
        .downcast_ref::<crate::host_functions::StoreQuotaExceeded>()
        .map(|quota| match quota.kind {
            crate::host_functions::StoreQuotaKind::Memory => "plugin memory quota exceeded",
            crate::host_functions::StoreQuotaKind::Table => "plugin table quota exceeded",
        })
}

fn call_with_quotas<T>(
    store: &mut Store<HostFunctions>,
    availability: &mut InstanceAvailability,
    call: impl FnOnce(&mut Store<HostFunctions>) -> wasmtime::Result<T>,
    validate: impl FnOnce(&T) -> std::result::Result<(), ResultValidationError>,
    map_ordinary_error: impl FnOnce(String) -> PluginError,
) -> Result<T> {
    availability.ensure_available()?;
    if prepare_export_quota(store).is_err() {
        return availability.mark_unavailable("plugin execution quota unavailable");
    }

    let value = match call(store) {
        Ok(value) => value,
        Err(error) => {
            if let Some(reason) = resource_quota_reason(&error) {
                return availability.mark_unavailable(reason);
            }
            return Err(map_ordinary_error(error.to_string()));
        }
    };

    match validate(&value) {
        Ok(()) => {}
        Err(ResultValidationError::Quota(violation)) => {
            return availability.mark_unavailable(violation.redacted_reason());
        }
        Err(ResultValidationError::Serialization(error)) => {
            return Err(PluginError::Serialization(error));
        }
    }
    Ok(value)
}

fn prepare_export_quota(store: &mut Store<HostFunctions>) -> wasmtime::Result<()> {
    store.set_fuel(FUEL_PER_EXPORT)?;
    store.set_epoch_deadline(EPOCH_TICKS_PER_EXPORT);
    Ok(())
}

fn new_plugin_store(
    engine: &Engine,
    host_functions: HostFunctions,
) -> Result<Store<HostFunctions>> {
    let mut store = Store::new(engine, host_functions);
    store.set_hostcall_fuel(HOSTCALL_FUEL_BYTES);
    store.limiter(|host| &mut host.store_limiter);
    prepare_export_quota(&mut store)
        .map_err(|_| PluginError::WasmError("failed to configure plugin fuel quota".to_string()))?;
    store.epoch_deadline_trap();
    Ok(store)
}

struct EpochTicker {
    control: Arc<(std::sync::Mutex<bool>, std::sync::Condvar)>,
    worker: Option<std::thread::JoinHandle<()>>,
    #[cfg(test)]
    exited: Arc<std::sync::atomic::AtomicBool>,
}

impl EpochTicker {
    fn spawn(engine: Engine) -> std::io::Result<Self> {
        let control = Arc::new((std::sync::Mutex::new(false), std::sync::Condvar::new()));
        let thread_control = control.clone();
        #[cfg(test)]
        let exited = Arc::new(std::sync::atomic::AtomicBool::new(false));
        #[cfg(test)]
        let thread_exited = exited.clone();
        let worker = std::thread::Builder::new()
            .name("arclain-wasm-epoch".to_string())
            .spawn(move || {
                let (stop, wake) = &*thread_control;
                let mut stopped = stop.lock().unwrap_or_else(|poisoned| poisoned.into_inner());
                loop {
                    let (next_stop, wait) = wake
                        .wait_timeout(stopped, EPOCH_TICK_INTERVAL)
                        .unwrap_or_else(|poisoned| poisoned.into_inner());
                    stopped = next_stop;
                    if *stopped {
                        break;
                    }
                    if wait.timed_out() {
                        engine.increment_epoch();
                    }
                }
                #[cfg(test)]
                thread_exited.store(true, std::sync::atomic::Ordering::Release);
            })?;

        Ok(Self {
            control,
            worker: Some(worker),
            #[cfg(test)]
            exited,
        })
    }
}

impl Drop for EpochTicker {
    fn drop(&mut self) {
        let (stop, wake) = &*self.control;
        *stop.lock().unwrap_or_else(|poisoned| poisoned.into_inner()) = true;
        wake.notify_one();
        if let Some(worker) = self.worker.take() {
            if worker.join().is_err() {
                tracing::warn!("WASM epoch ticker terminated unexpectedly");
            }
        }
    }
}

/// WASM runtime for executing plugins
pub struct WasmRuntime {
    engine: Engine,
    epoch_ticker: Arc<EpochTicker>,
}

impl WasmRuntime {
    /// Create a new WASM runtime
    pub fn new() -> Result<Self> {
        let mut config = Config::new();
        config.wasm_component_model(true); // Enable component model
        config.consume_fuel(true);
        config.epoch_interruption(true);

        let engine = Engine::new(&config).map_err(|e| PluginError::WasmError(e.to_string()))?;
        let epoch_ticker = Arc::new(EpochTicker::spawn(engine.clone()).map_err(|_| {
            PluginError::WasmError("failed to start WASM epoch ticker".to_string())
        })?);

        info!("WASM runtime initialized (Component Model enabled)");
        Ok(Self {
            engine,
            epoch_ticker,
        })
    }

    #[cfg(test)]
    fn epoch_ticker_exit_probe(&self) -> Arc<std::sync::atomic::AtomicBool> {
        self.epoch_ticker.exited.clone()
    }

    /// Load a WASM component from a file
    pub fn load_module(&self, id: String, path: &Path) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from: {}", path.display());

        let component = Component::from_file(&self.engine, path)
            .map_err(|e| PluginError::LoadError(format!("Failed to load component: {}", e)))?;

        info!("WASM component loaded successfully: {}", path.display());

        Ok(LoadedPlugin {
            id,
            component,
            engine: self.engine.clone(),
            epoch_ticker: self.epoch_ticker.clone(),
            _path: path.to_path_buf(),
        })
    }

    /// Load a WASM component from bytes
    pub fn load_module_from_bytes(&self, id: String, bytes: &[u8]) -> Result<LoadedPlugin> {
        debug!("Loading WASM component from bytes ({} bytes)", bytes.len());

        let component = Component::from_binary(&self.engine, bytes)
            .map_err(|e| PluginError::LoadError(e.to_string()))?;

        info!("WASM component loaded successfully from bytes");

        Ok(LoadedPlugin {
            id,
            component,
            engine: self.engine.clone(),
            epoch_ticker: self.epoch_ticker.clone(),
            _path: std::path::PathBuf::from("<bytes>"),
        })
    }
}

/// A loaded WASM plugin ready for execution
pub struct LoadedPlugin {
    pub id: String,
    component: Component,
    engine: Engine,
    epoch_ticker: Arc<EpochTicker>,
    _path: std::path::PathBuf,
}

impl LoadedPlugin {
    /// Instantiate a plugin with its host-function state.
    ///
    /// Pre-bridge this had a `_with_backend` sibling that handed an
    /// `Arc<dyn ArchiveBackend>` to the host so `list_archive_files`
    /// could re-list the archive. That path is gone: the host reads
    /// the active tab's already-listed entries through the
    /// `ActiveTabBridge`, so no plugin needs raw backend access. The
    /// backend param (and the `with_backend` constructors it fed)
    /// were dead after that rewire.
    pub fn instantiate(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
        library_service: Option<Arc<arclain_core::LibraryService>>,
        settings: HashMap<String, String>,
        active_tab_bridge: Option<Arc<dyn crate::ActiveTabBridge>>,
    ) -> Result<PluginInstance> {
        let host_funcs = HostFunctions::new(
            self.id.clone(),
            capabilities.into_iter().collect(),
            requests_per_minute,
            settings,
        )?;

        self.instantiate_with_host_functions(host_funcs, library_service, active_tab_bridge)
    }

    pub(crate) fn instantiate_with_plugin_log_dir(
        &self,
        capabilities: Vec<PluginCapability>,
        requests_per_minute: u32,
        library_service: Option<Arc<arclain_core::LibraryService>>,
        settings: HashMap<String, String>,
        active_tab_bridge: Option<Arc<dyn crate::ActiveTabBridge>>,
        plugin_log_dir: &Path,
    ) -> Result<PluginInstance> {
        let host_funcs = HostFunctions::new_with_plugin_log_dir(
            self.id.clone(),
            capabilities.into_iter().collect(),
            requests_per_minute,
            settings,
            plugin_log_dir,
        )?;

        self.instantiate_with_host_functions(host_funcs, library_service, active_tab_bridge)
    }

    pub(crate) fn instantiate_for_metadata_validation(&self) -> Result<PluginInstance> {
        let host_funcs = HostFunctions::new_for_metadata_validation(self.id.clone())?;
        self.instantiate_with_host_functions(host_funcs, None, None)
    }

    fn instantiate_with_host_functions(
        &self,
        mut host_funcs: HostFunctions,
        library_service: Option<Arc<arclain_core::LibraryService>>,
        active_tab_bridge: Option<Arc<dyn crate::ActiveTabBridge>>,
    ) -> Result<PluginInstance> {
        if let Some(lib_svc) = library_service {
            host_funcs.set_library_service(lib_svc);
        }

        host_funcs.active_tab = active_tab_bridge;

        let mut store = new_plugin_store(&self.engine, host_funcs)?;
        let mut linker = Linker::new(&self.engine);

        // Link WASI functions
        wasmtime_wasi::p2::add_to_linker_sync(&mut linker)
            .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Link host functions
        crate::PluginWorld::add_to_linker::<_, HasSelf<_>>(
            &mut linker,
            |state: &mut HostFunctions| state,
        )
        .map_err(|e| PluginError::InitError(e.to_string()))?;

        // Instantiate the component
        prepare_export_quota(&mut store).map_err(|_| {
            PluginError::Unavailable("plugin execution quota unavailable".to_string())
        })?;
        let plugin =
            PluginWorld::instantiate(&mut store, &self.component, &linker).map_err(|error| {
                match resource_quota_reason(&error) {
                    Some(reason) => PluginError::Unavailable(reason.to_string()),
                    None => PluginError::InitError(error.to_string()),
                }
            })?;

        debug!("Plugin instance created");

        Ok(PluginInstance {
            store,
            plugin,
            metadata: None,
            availability: InstanceAvailability::default(),
            _epoch_ticker: self.epoch_ticker.clone(),
        })
    }
}

/// An instantiated plugin that can receive events
pub struct PluginInstance {
    store: Store<HostFunctions>,
    plugin: PluginWorld,
    metadata: Option<PluginMetadata>,
    availability: InstanceAvailability,
    _epoch_ticker: Arc<EpochTicker>,
}

impl PluginInstance {
    fn call_export<T>(
        &mut self,
        call: impl FnOnce(&PluginWorld, &mut Store<HostFunctions>) -> wasmtime::Result<T>,
        validate: impl FnOnce(&T) -> std::result::Result<(), ResultValidationError>,
        map_ordinary_error: impl FnOnce(String) -> PluginError,
    ) -> Result<T> {
        let Self {
            store,
            plugin,
            availability,
            ..
        } = self;
        call_with_quotas(
            store,
            availability,
            |store| call(plugin, store),
            validate,
            map_ordinary_error,
        )
    }

    /// Return the host-generated reason this instance was made terminal.
    /// Guest-provided error details are never stored here.
    pub fn unavailable_reason(&self) -> Option<&str> {
        self.availability.reason()
    }

    /// Initialize the plugin
    pub fn init(&mut self) -> Result<()> {
        self.call_export(
            |plugin, store| plugin.call_init(store),
            |_| Ok(()),
            PluginError::InitError,
        )?;

        debug!("Plugin initialized successfully");
        Ok(())
    }

    /// Get plugin metadata.
    ///
    /// Cached per-instance after the first WIT call. Plugins built
    /// against the post-2026-05-07 WIT export `get-metadata` and
    /// self-report id/name/version/author/description; the host caches
    /// the result so repeated calls don't re-cross the WASM boundary
    /// (the manager's `install_plugin` flow asks once at install time
    /// to derive a stable plugin id for the manifest it writes).
    pub fn get_metadata(&mut self) -> Result<PluginMetadata> {
        self.availability.ensure_available()?;
        if let Some(metadata) = &self.metadata {
            return Ok(metadata.clone());
        }

        let metadata = self.call_export(
            |plugin, store| {
                plugin
                    .call_get_metadata(store)
                    .map(|metadata| PluginMetadata {
                        id: metadata.id,
                        name: metadata.name,
                        version: metadata.version,
                        author: metadata.author,
                        description: metadata.description,
                    })
            },
            validate_serialized_result,
            PluginError::ExecutionError,
        )?;
        self.metadata = Some(metadata.clone());
        Ok(metadata)
    }

    /// Get the organization rules supplied by this plugin.
    pub fn get_default_rules(&mut self) -> Result<Vec<arclain_core::OrganizationRule>> {
        self.call_export(
            |plugin, store| {
                plugin.call_get_default_rules(store).map(|rules| {
                    rules
                        .into_iter()
                        .map(arclain_core::OrganizationRule::from)
                        .collect()
                })
            },
            validate_serialized_result,
            PluginError::ExecutionError,
        )
    }

    /// Get UI layout for a specific extension point
    pub fn get_ui_layout(
        &mut self,
        extension_point: PluginExtensionPoint,
    ) -> Result<crate::types::PluginLayout> {
        let ep_str = match extension_point {
            PluginExtensionPoint::MainPage => "MainPage".to_string(),
            PluginExtensionPoint::PluginButton => "PluginButton".to_string(),
            PluginExtensionPoint::Panel => "Panel".to_string(),
            PluginExtensionPoint::Dialog(ref id) => format!("Dialog:{}", id),
            PluginExtensionPoint::Page(ref id) => format!("Page:{}", id),
        };

        self.call_export(
            |plugin, store| {
                plugin
                    .call_get_ui_layout(store, &ep_str)
                    .map(convert_plugin_layout)
            },
            validate_layout_result,
            PluginError::ExecutionError,
        )
    }

    /// Send a UI event to the plugin and get actions back
    pub fn send_ui_event(
        &mut self,
        element_id: &str,
        value: Option<String>,
    ) -> Result<Vec<crate::types::PluginAction>> {
        debug!(
            "PluginInstance::send_ui_event: Calling plugin handler for {}",
            element_id
        );

        let actions = self.call_export::<Vec<crate::types::PluginAction>>(
            |plugin, store| {
                plugin
                    .call_on_ui_event(store, element_id, value.as_deref())
                    .map(|actions| {
                        actions
                            .into_iter()
                            .map(convert_plugin_action)
                            .collect::<Vec<_>>()
                    })
            },
            |actions| validate_actions_result(actions),
            |message| {
                error!(
                    "PluginInstance::send_ui_event: Failed to call plugin: {}",
                    message
                );
                PluginError::ExecutionError(message)
            },
        )?;

        debug!(
            "PluginInstance::send_ui_event: Plugin returned {} actions",
            actions.len()
        );

        Ok(actions)
    }

    /// Clean up the plugin
    pub fn cleanup(&mut self) -> Result<()> {
        // Cleanup is handled by Drop in Component Model usually,
        // or we can add a specific cleanup function to WIT
        Ok(())
    }

    /// Set the content cache for host functions
    pub fn set_content_cache(&mut self, cache: Option<Arc<arclain_data::ContentCache>>) {
        let host = self.store.data_mut();
        match cache {
            Some(c) => host.set_content_cache(c),
            None => host.content_cache = None,
        }
    }

    /// Set the resource manager for host functions
    pub fn set_resource_manager(&mut self, manager: Option<Arc<arclain_data::ResourceManager>>) {
        let host = self.store.data_mut();
        match manager {
            Some(m) => host.set_resource_manager(m),
            None => host.resource_manager = None,
        }
    }

    /// Install the bridge to the host's per-tab signal tree for this
    /// instance. Replaces the pre-bridge `set_metadata_signal` +
    /// `set_archive_context` pair — see `crate::active_tab`.
    pub fn set_active_tab_bridge(&mut self, bridge: Arc<dyn crate::ActiveTabBridge>) {
        self.store.data_mut().set_active_tab_bridge(bridge);
    }

    /// Install (or clear) the per-event context for this instance.
    /// The dispatch worker wraps `send_ui_event` with set / clear
    /// calls so host-function reads inside the handler resolve to
    /// the originating tab.
    pub fn set_event_context(&mut self, ctx: Option<crate::host_functions::EventContext>) {
        self.store.data_mut().set_event_context(ctx);
    }

    /// Set the async HTTP client for host functions
    pub fn set_async_http_client(&mut self, client: Option<Arc<arclain_network::AsyncHttpClient>>) {
        let host = self.store.data_mut();
        match client {
            Some(c) => host.set_async_http_client(c),
            None => host.async_http_client = None,
        }
    }

    /// Set the library service for host functions
    pub fn set_library_service(&mut self, lib_svc: Option<Arc<arclain_core::LibraryService>>) {
        let host = self.store.data_mut();
        match lib_svc {
            Some(c) => host.set_library_service(c),
            None => host.library_service = None,
        }
    }

    /// Set the gameta server client for host functions
    pub fn set_gameta_client(
        &mut self,
        client: Option<Arc<arclain_network::features::gameta_client::GametaClient>>,
    ) {
        let host = self.store.data_mut();
        match client {
            Some(c) => host.set_gameta_client(c),
            None => host.gameta_client = None,
        }
    }

    /// Get gameta client reference (if configured)
    pub fn get_gameta_client(
        &self,
    ) -> Option<Arc<arclain_network::features::gameta_client::GametaClient>> {
        let data = self.store.data();
        data.gameta_client.clone()
    }

    /// Get a handle to the active-tab bridge if one has been
    /// installed. Used by the dispatch worker to snapshot per-tab
    /// signals at event-fire time.
    pub fn get_active_tab_bridge(&self) -> Option<Arc<dyn crate::ActiveTabBridge>> {
        let data = self.store.data();
        data.active_tab.clone()
    }

    /// Get network logs from the plugin
    pub fn get_network_log(&self) -> Vec<(std::time::SystemTime, String)> {
        let data = self.store.data();
        let logs = data.network_log.lock();
        logs.clone()
    }

    /// Get current settings from the plugin
    pub fn get_settings(&self) -> Option<std::collections::HashMap<String, String>> {
        let data = self.store.data();
        let settings = data.settings.lock();
        Some(settings.clone())
    }

    /// Cheap clone of the plugin's `settings_dirty` flag — checked by
    /// `PluginManager::get_all_settings` without taking the instance
    /// lock (audit P14).
    pub fn settings_dirty_handle(&self) -> std::sync::Arc<std::sync::atomic::AtomicBool> {
        self.store.data().settings_dirty.clone()
    }

    /// Get top-level tabs registered by this plugin
    pub fn get_top_tabs(&mut self) -> Result<Vec<crate::types::TopTabConfig>> {
        self.call_export(
            |plugin, store| {
                plugin
                    .call_get_top_tabs(store)
                    .map(|tabs| tabs.into_iter().map(convert_top_tab_config).collect())
            },
            validate_serialized_result,
            PluginError::ExecutionError,
        )
    }
}

#[cfg(test)]
mod resource_limit_tests {
    use super::*;

    #[cfg(any(windows, target_os = "linux"))]
    const LARGE_LIFT_BYTES: usize = 120 * 1024 * 1024;
    #[cfg(any(windows, target_os = "linux"))]
    const HOSTCALL_MEMORY_CHILD: &str = "ARCLAIN_HOSTCALL_MEMORY_CHILD";
    type ByteListLift = wasmtime::component::TypedFunc<(), (Vec<u8>,)>;

    fn instantiate_byte_list_fixture(
        runtime: &WasmRuntime,
        byte_len: usize,
    ) -> anyhow::Result<(Store<HostFunctions>, ByteListLift)> {
        let memory_pages = (byte_len + 8).div_ceil(64 * 1024);
        let length_bytes = (byte_len as u32).to_le_bytes();
        let encoded_length = length_bytes
            .iter()
            .map(|byte| format!("\\{byte:02x}"))
            .collect::<String>();
        let component = Component::new(
            &runtime.engine,
            format!(
                r#"
                    (component
                        (core module $fixture
                            (memory (export "memory") {memory_pages})
                            (data (i32.const 0) "\08\00\00\00{encoded_length}")
                            (func (export "lift") (result i32)
                                i32.const 0))
                        (core instance $instance (instantiate $fixture))
                        (alias core export $instance "memory" (core memory $memory))
                        (alias core export $instance "lift" (core func $lift))
                        (type $bytes (list u8))
                        (type $lift-type (func (result $bytes)))
                        (func (export "lift") (type $lift-type)
                            (canon lift (core func $lift) (memory $memory))))
                "#,
            ),
        )?;
        let host = HostFunctions::new_for_metadata_validation("hostcall-lift-test".to_string())?;
        let mut store = new_plugin_store(&runtime.engine, host)?;
        let instance = Linker::new(&runtime.engine).instantiate(&mut store, &component)?;
        let lift = instance.get_typed_func::<(), (Vec<u8>,)>(&mut store, "lift")?;
        Ok((store, lift))
    }

    #[cfg(windows)]
    fn current_working_set_bytes() -> usize {
        use std::ffi::c_void;

        #[repr(C)]
        struct ProcessMemoryCounters {
            cb: u32,
            page_fault_count: u32,
            peak_working_set_size: usize,
            working_set_size: usize,
            quota_peak_paged_pool_usage: usize,
            quota_paged_pool_usage: usize,
            quota_peak_non_paged_pool_usage: usize,
            quota_non_paged_pool_usage: usize,
            pagefile_usage: usize,
            peak_pagefile_usage: usize,
        }

        #[link(name = "kernel32")]
        extern "system" {
            fn GetCurrentProcess() -> *mut c_void;
        }
        #[link(name = "psapi")]
        extern "system" {
            fn GetProcessMemoryInfo(
                process: *mut c_void,
                counters: *mut ProcessMemoryCounters,
                size: u32,
            ) -> i32;
        }

        let mut counters = ProcessMemoryCounters {
            cb: std::mem::size_of::<ProcessMemoryCounters>() as u32,
            page_fault_count: 0,
            peak_working_set_size: 0,
            working_set_size: 0,
            quota_peak_paged_pool_usage: 0,
            quota_paged_pool_usage: 0,
            quota_peak_non_paged_pool_usage: 0,
            quota_non_paged_pool_usage: 0,
            pagefile_usage: 0,
            peak_pagefile_usage: 0,
        };
        // SAFETY: both functions are called with the current process pseudo-handle
        // and a correctly sized writable PROCESS_MEMORY_COUNTERS buffer.
        let succeeded = unsafe {
            GetProcessMemoryInfo(
                GetCurrentProcess(),
                &mut counters,
                std::mem::size_of::<ProcessMemoryCounters>() as u32,
            )
        };
        assert_ne!(succeeded, 0, "GetProcessMemoryInfo must succeed");
        counters.working_set_size
    }

    #[cfg(target_os = "linux")]
    fn current_working_set_bytes() -> usize {
        let status = std::fs::read_to_string("/proc/self/status").unwrap();
        let rss_kib = status
            .lines()
            .find_map(|line| line.strip_prefix("VmRSS:"))
            .and_then(|value| value.split_whitespace().next())
            .and_then(|value| value.parse::<usize>().ok())
            .expect("/proc/self/status must contain VmRSS");
        rss_kib * 1024
    }

    fn instantiate_resource_fixture(
        runtime: &WasmRuntime,
        core_module: &str,
    ) -> wasmtime::Result<()> {
        let component = Component::new(&runtime.engine, resource_fixture_wat(core_module))?;
        let host = HostFunctions::new_for_metadata_validation("resource-limit-test".to_string())
            .expect("test plugin ID must be valid");
        let mut store =
            new_plugin_store(&runtime.engine, host).expect("test store configuration must succeed");
        let linker = Linker::new(&runtime.engine);
        linker.instantiate(&mut store, &component)?;
        Ok(())
    }

    fn instantiate_core_instance_fixture(
        runtime: &WasmRuntime,
        count: usize,
    ) -> wasmtime::Result<()> {
        let component = Component::new(&runtime.engine, core_instance_fixture_wat(count))?;
        let host = HostFunctions::new_for_metadata_validation("instance-limit-test".to_string())
            .expect("test plugin ID must be valid");
        let mut store =
            new_plugin_store(&runtime.engine, host).expect("test store configuration must succeed");
        Linker::new(&runtime.engine).instantiate(&mut store, &component)?;
        Ok(())
    }

    fn resource_fixture_wat(core_module: &str) -> String {
        format!(
            "(component (core module $fixture {core_module}) (core instance $instance (instantiate $fixture)))"
        )
    }

    fn core_instance_fixture_wat(count: usize) -> String {
        let instances = "(core instance (instantiate $fixture))".repeat(count);
        format!("(component (core module $fixture) {instances})")
    }

    fn push_u32_leb(bytes: &mut Vec<u8>, mut value: usize) {
        loop {
            let mut byte = (value & 0x7f) as u8;
            value >>= 7;
            if value != 0 {
                byte |= 0x80;
            }
            bytes.push(byte);
            if value == 0 {
                return;
            }
        }
    }

    fn read_u32_leb(bytes: &[u8], cursor: &mut usize) -> usize {
        let mut value = 0usize;
        let mut shift = 0usize;
        loop {
            let byte = bytes[*cursor];
            *cursor += 1;
            value |= usize::from(byte & 0x7f) << shift;
            if byte & 0x80 == 0 {
                return value;
            }
            shift += 7;
        }
    }

    fn plugin_with_extra_core_instances(
        base: &[u8],
        core_module: &[u8],
        instance_count: usize,
    ) -> Vec<u8> {
        const COMPONENT_HEADER_BYTES: usize = 8;
        const CORE_MODULE_SECTION: u8 = 1;
        const CORE_INSTANCE_SECTION: u8 = 2;

        let mut cursor = COMPONENT_HEADER_BYTES;
        let mut module_index = 0usize;
        while cursor < base.len() {
            let section_id = base[cursor];
            cursor += 1;
            let section_len = read_u32_leb(base, &mut cursor);
            if section_id == CORE_MODULE_SECTION {
                module_index += 1;
            }
            cursor += section_len;
        }
        assert_eq!(cursor, base.len());

        let mut bytes = base.to_vec();
        bytes.push(CORE_MODULE_SECTION);
        push_u32_leb(&mut bytes, core_module.len());
        bytes.extend_from_slice(core_module);

        let mut instances = Vec::new();
        push_u32_leb(&mut instances, instance_count);
        for _ in 0..instance_count {
            instances.push(0x00);
            push_u32_leb(&mut instances, module_index);
            instances.push(0x00);
        }
        bytes.push(CORE_INSTANCE_SECTION);
        push_u32_leb(&mut bytes, instances.len());
        bytes.extend(instances);
        bytes
    }

    fn loaded_binary_fixture(runtime: &WasmRuntime, id: &str, bytes: &[u8]) -> LoadedPlugin {
        LoadedPlugin {
            id: id.to_string(),
            component: Component::from_binary(&runtime.engine, bytes).unwrap(),
            engine: runtime.engine.clone(),
            epoch_ticker: runtime.epoch_ticker.clone(),
            _path: std::path::PathBuf::from("<resource-limit-test>"),
        }
    }

    fn assert_unavailable_reason(result: Result<PluginInstance>, expected: &str) {
        match result {
            Err(PluginError::Unavailable(reason)) => assert_eq!(reason, expected),
            Err(error) => panic!("expected redacted unavailable error, got {error}"),
            Ok(_) => panic!("resource-limit fixture unexpectedly instantiated"),
        }
    }

    #[test]
    fn runtime_engine_enables_fuel_metering() {
        let runtime = WasmRuntime::new().unwrap();
        let mut store = Store::new(&runtime.engine, ());

        store
            .set_fuel(1)
            .expect("every runtime store must support fuel metering");
    }

    // Working-set telemetry is deliberately OS-specific; functional boundary
    // coverage for hostcall fuel remains platform-independent below.
    #[cfg(any(windows, target_os = "linux"))]
    #[test]
    fn hostcall_fuel_prevents_large_prevalidation_lift_allocation() {
        if std::env::var_os(HOSTCALL_MEMORY_CHILD).is_some() {
            let runtime = WasmRuntime::new().unwrap();
            let (mut store, lift) =
                instantiate_byte_list_fixture(&runtime, LARGE_LIFT_BYTES).unwrap();
            let before = current_working_set_bytes();
            let lifted = lift.call(&mut store, ()).ok();
            std::hint::black_box(&lifted);
            let delta = current_working_set_bytes().saturating_sub(before);
            println!(
                "ARCLAIN_HOSTCALL_MEASUREMENT lifted={} rss_delta={delta}",
                lifted.is_some()
            );
            return;
        }

        let output = std::process::Command::new(std::env::current_exe().unwrap())
            .args([
                "--exact",
                "runtime::resource_limit_tests::hostcall_fuel_prevents_large_prevalidation_lift_allocation",
                "--nocapture",
            ])
            .env(HOSTCALL_MEMORY_CHILD, "1")
            .output()
            .unwrap();
        let stdout = String::from_utf8(output.stdout).unwrap();
        let measurement = stdout
            .lines()
            .find(|line| line.contains("ARCLAIN_HOSTCALL_MEASUREMENT"))
            .unwrap_or_else(|| panic!("child did not report memory measurement:\n{stdout}"));
        let lifted = measurement.contains("lifted=true");
        let delta = measurement
            .split("rss_delta=")
            .nth(1)
            .and_then(|value| value.parse::<usize>().ok())
            .unwrap();

        assert!(
            !lifted && delta < 32 * 1024 * 1024,
            "a 120 MiB guest result was lifted before validation: {measurement}"
        );
    }

    #[test]
    fn configured_hostcall_fuel_covers_measured_current_wit_shapes() {
        use crate::arclain::plugin::rules::PluginRuleDefinition as WitRule;
        use crate::arclain::plugin::ui::{
            KeyValuePair as WitKeyValuePair, ListItemConfig as WitListItem,
            PluginAction as WitAction, ToolbarButtonConfig as WitToolbarButton,
            TopTabConfig as WitTopTab, UiElement as WitUiElement,
        };

        const DOCUMENTED_HOSTCALL_FUEL_BYTES: usize = 8 * 1024 * 1024;

        fn max_serialized_list_len<T: Serialize>(minimum_item: &T) -> usize {
            let item_bytes = serde_json::to_vec(minimum_item).unwrap().len();
            (MAX_SERIALIZED_RESULT_BYTES - 2) / (item_bytes + 1) + 1
        }

        let largest_ui_allocation = [
            std::mem::size_of::<WitUiElement>(),
            std::mem::size_of::<WitListItem>(),
            std::mem::size_of::<WitToolbarButton>(),
            std::mem::size_of::<WitKeyValuePair>(),
            std::mem::size_of::<(String, Option<String>)>(),
            std::mem::size_of::<String>(),
        ]
        .into_iter()
        .max()
        .unwrap();
        let layout_bytes =
            MAX_SERIALIZED_RESULT_BYTES + MAX_UI_ELEMENTS.saturating_mul(largest_ui_allocation);

        let action_bytes = MAX_SERIALIZED_RESULT_BYTES
            + MAX_ACTIONS.saturating_mul(
                std::mem::size_of::<WitAction>() + std::mem::size_of::<(String, Option<String>)>(),
            );

        let minimum_tab = crate::types::TopTabConfig {
            id: String::new(),
            label: String::new(),
            icon: String::new(),
            badge: None,
            priority: 0,
        };
        let top_tab_bytes = MAX_SERIALIZED_RESULT_BYTES
            + max_serialized_list_len(&minimum_tab)
                .saturating_mul(std::mem::size_of::<WitTopTab>());

        let minimum_rule = arclain_core::OrganizationRule::default();
        let rule_bytes = MAX_SERIALIZED_RESULT_BYTES
            + max_serialized_list_len(&minimum_rule).saturating_mul(std::mem::size_of::<WitRule>());

        let worst_shape_bytes = [layout_bytes, action_bytes, top_tab_bytes, rule_bytes]
            .into_iter()
            .max()
            .unwrap();
        assert!(
            worst_shape_bytes <= DOCUMENTED_HOSTCALL_FUEL_BYTES,
            "current WIT host shape needs {worst_shape_bytes} bytes of hostcall fuel"
        );

        let runtime = WasmRuntime::new().unwrap();
        let host =
            HostFunctions::new_for_metadata_validation("hostcall-budget".to_string()).unwrap();
        let store = new_plugin_store(&runtime.engine, host).unwrap();
        assert_eq!(
            store.hostcall_fuel(),
            DOCUMENTED_HOSTCALL_FUEL_BYTES,
            "production stores must use the measured current-WIT hostcall budget; estimates: layout={layout_bytes}, actions={action_bytes}, tabs={top_tab_bytes}, rules={rule_bytes}"
        );
    }

    #[test]
    fn hostcall_fuel_accepts_exact_boundary_and_terminally_rejects_one_over() {
        let runtime = WasmRuntime::new().unwrap();
        let (mut exact_store, exact_lift) =
            instantiate_byte_list_fixture(&runtime, HOSTCALL_FUEL_BYTES).unwrap();
        let exact = exact_lift.call(&mut exact_store, ()).unwrap().0;
        assert_eq!(exact.len(), HOSTCALL_FUEL_BYTES);

        let (mut over_store, over_lift) =
            instantiate_byte_list_fixture(&runtime, HOSTCALL_FUEL_BYTES + 1).unwrap();
        let mut availability = InstanceAvailability::default();
        let call_entries = std::sync::atomic::AtomicUsize::new(0);
        let first = call_with_quotas(
            &mut over_store,
            &mut availability,
            |store| {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                over_lift.call(store, ()).map(|_| ())
            },
            |_| Ok(()),
            PluginError::ExecutionError,
        )
        .unwrap_err();
        let second = call_with_quotas(
            &mut over_store,
            &mut availability,
            |store| {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                over_lift.call(store, ()).map(|_| ())
            },
            |_| Ok(()),
            PluginError::ExecutionError,
        )
        .unwrap_err();

        assert!(matches!(
            first,
            PluginError::Unavailable(ref reason)
                if reason == "plugin hostcall data quota exceeded"
        ));
        assert!(matches!(second, PluginError::Unavailable(_)));
        assert_eq!(call_entries.load(std::sync::atomic::Ordering::SeqCst), 1);
        assert_eq!(
            availability.reason(),
            Some("plugin hostcall data quota exceeded")
        );
    }

    #[test]
    fn fuel_epoch_memory_and_table_quota_errors_have_redacted_classifications() {
        let fuel = wasmtime::Error::from(wasmtime::Trap::OutOfFuel);
        let epoch = wasmtime::Error::from(wasmtime::Trap::Interrupt);
        let memory = wasmtime::Error::new(crate::host_functions::StoreQuotaExceeded {
            kind: crate::host_functions::StoreQuotaKind::Memory,
        });
        let table = wasmtime::Error::new(crate::host_functions::StoreQuotaExceeded {
            kind: crate::host_functions::StoreQuotaKind::Table,
        });

        assert_eq!(
            resource_quota_reason(&fuel),
            Some("plugin fuel quota exceeded")
        );
        assert_eq!(
            resource_quota_reason(&epoch),
            Some("plugin execution deadline exceeded")
        );
        assert_eq!(
            resource_quota_reason(&memory),
            Some("plugin memory quota exceeded")
        );
        assert_eq!(
            resource_quota_reason(&table),
            Some("plugin table quota exceeded")
        );
    }

    #[test]
    fn serialized_result_limit_accepts_exact_boundary_and_rejects_one_byte_over() {
        let exact = "x".repeat(MAX_SERIALIZED_RESULT_BYTES - 2);
        let over = "x".repeat(MAX_SERIALIZED_RESULT_BYTES - 1);

        assert!(validate_serialized_result(&exact).is_ok());
        assert!(matches!(
            validate_serialized_result(&over),
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        ));
    }

    #[test]
    fn ui_element_limit_counts_nested_elements_at_the_boundary() {
        use crate::types::{PluginLayout, PluginUiElement};

        let nested_items = vec![PluginUiElement::Separator; MAX_UI_ELEMENTS - 1];
        let exact = PluginLayout::Single {
            elements: vec![PluginUiElement::ListContainer {
                id: "items".to_string(),
                items: nested_items,
                max_height: None,
                empty_message: None,
            }],
        };
        assert!(validate_layout_result(&exact).is_ok());

        let over = PluginLayout::Single {
            elements: vec![PluginUiElement::Separator; MAX_UI_ELEMENTS + 1],
        };
        assert!(matches!(
            validate_layout_result(&over),
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        ));
    }

    #[test]
    fn every_rendered_layout_collection_counts_boundary_and_one_over() {
        use crate::types::{KeyValuePair, PluginLayout, PluginUiElement, ToolbarButton};

        let strings = |count| vec![String::new(); count];
        let toolbar_buttons = |count| {
            vec![
                ToolbarButton {
                    id: String::new(),
                    label: String::new(),
                    icon: None,
                    primary: false,
                    spacer_before: false,
                };
                count
            ]
        };
        let pairs = |count| {
            vec![
                KeyValuePair {
                    key: String::new(),
                    value: String::new(),
                };
                count
            ]
        };
        let images = |count| vec![(String::new(), None); count];
        let single = |element| PluginLayout::Single {
            elements: vec![element],
        };

        let cases = vec![
            (
                "radio options",
                single(PluginUiElement::RadioGroup {
                    id: String::new(),
                    label: String::new(),
                    options: strings(MAX_UI_ELEMENTS - 1),
                    selected: String::new(),
                }),
                single(PluginUiElement::RadioGroup {
                    id: String::new(),
                    label: String::new(),
                    options: strings(MAX_UI_ELEMENTS),
                    selected: String::new(),
                }),
            ),
            (
                "dropdown options",
                single(PluginUiElement::Dropdown {
                    id: String::new(),
                    label: String::new(),
                    options: strings(MAX_UI_ELEMENTS - 1),
                    selected: String::new(),
                }),
                single(PluginUiElement::Dropdown {
                    id: String::new(),
                    label: String::new(),
                    options: strings(MAX_UI_ELEMENTS),
                    selected: String::new(),
                }),
            ),
            (
                "tabs",
                single(PluginUiElement::Tabs {
                    id: String::new(),
                    tabs: strings(MAX_UI_ELEMENTS - 1),
                    selected: String::new(),
                }),
                single(PluginUiElement::Tabs {
                    id: String::new(),
                    tabs: strings(MAX_UI_ELEMENTS),
                    selected: String::new(),
                }),
            ),
            (
                "toolbar buttons",
                single(PluginUiElement::Toolbar {
                    buttons: toolbar_buttons(MAX_UI_ELEMENTS - 1),
                }),
                single(PluginUiElement::Toolbar {
                    buttons: toolbar_buttons(MAX_UI_ELEMENTS),
                }),
            ),
            (
                "carousel images",
                single(PluginUiElement::Carousel {
                    id: String::new(),
                    images: images(MAX_UI_ELEMENTS - 1),
                    current_index: 0,
                    max_height: None,
                    thumbnail_height: None,
                    enable_lightbox: true,
                }),
                single(PluginUiElement::Carousel {
                    id: String::new(),
                    images: images(MAX_UI_ELEMENTS),
                    current_index: 0,
                    max_height: None,
                    thumbnail_height: None,
                    enable_lightbox: true,
                }),
            ),
            (
                "key-value list items",
                single(PluginUiElement::KeyValueList {
                    items: pairs(MAX_UI_ELEMENTS - 1),
                    columns: None,
                }),
                single(PluginUiElement::KeyValueList {
                    items: pairs(MAX_UI_ELEMENTS),
                    columns: None,
                }),
            ),
            (
                "metadata grid items",
                single(PluginUiElement::MetadataGrid {
                    items: pairs(MAX_UI_ELEMENTS - 1),
                    columns: None,
                }),
                single(PluginUiElement::MetadataGrid {
                    items: pairs(MAX_UI_ELEMENTS),
                    columns: None,
                }),
            ),
            (
                "tag chips",
                single(PluginUiElement::TagChips {
                    tags: strings(MAX_UI_ELEMENTS - 1),
                    max_display: None,
                }),
                single(PluginUiElement::TagChips {
                    tags: strings(MAX_UI_ELEMENTS),
                    max_display: None,
                }),
            ),
        ];

        for (name, exact, over) in cases {
            assert!(
                validate_layout_result(&exact).is_ok(),
                "{name} must accept the exact rendered-work boundary"
            );
            assert!(
                matches!(
                    validate_layout_result(&over),
                    Err(ResultValidationError::Quota(QuotaViolation::Result))
                ),
                "{name} must reject one rendered work item over"
            );
        }
    }

    #[test]
    fn tag_chip_work_matches_visible_tags_plus_overflow_label() {
        let layout = crate::types::PluginLayout::Single {
            elements: vec![crate::types::PluginUiElement::TagChips {
                tags: vec![String::new(); MAX_UI_ELEMENTS + 1],
                max_display: Some(0),
            }],
        };

        assert!(
            validate_layout_result(&layout).is_ok(),
            "zero visible tags render one element plus the +N-more label"
        );
    }

    #[test]
    fn split_nested_layout_combines_all_rendered_work() {
        use crate::types::{PluginLayout, PluginUiElement, ToolbarButton};

        let layout = |button_count| PluginLayout::Split {
            sidebar: vec![PluginUiElement::ListContainer {
                id: String::new(),
                items: vec![PluginUiElement::Separator; 4_998],
                max_height: None,
                empty_message: None,
            }],
            content: vec![PluginUiElement::Toolbar {
                buttons: vec![
                    ToolbarButton {
                        id: String::new(),
                        label: String::new(),
                        icon: None,
                        primary: false,
                        spacer_before: false,
                    };
                    button_count
                ],
            }],
            sidebar_width: None,
        };

        assert!(validate_layout_result(&layout(5_000)).is_ok());
        assert!(matches!(
            validate_layout_result(&layout(5_001)),
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        ));
    }

    #[test]
    fn action_limit_accepts_boundary_and_rejects_one_over() {
        let exact = vec![crate::types::PluginAction::None; MAX_ACTIONS];
        let over = vec![crate::types::PluginAction::None; MAX_ACTIONS + 1];

        assert!(validate_actions_result(&exact).is_ok());
        assert!(matches!(
            validate_actions_result(&over),
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        ));
    }

    #[test]
    fn lightbox_images_share_the_action_work_budget() {
        let action = |image_count| {
            vec![crate::types::PluginAction::OpenLightbox {
                images: vec![(String::new(), None); image_count],
                start_index: 0,
                title: None,
            }]
        };

        assert!(validate_actions_result(&action(MAX_ACTIONS - 1)).is_ok());
        assert!(matches!(
            validate_actions_result(&action(MAX_ACTIONS)),
            Err(ResultValidationError::Quota(QuotaViolation::Result))
        ));
    }

    #[test]
    fn linear_memory_limit_accepts_boundary_and_rejects_one_page_over() {
        let runtime = WasmRuntime::new().unwrap();

        instantiate_resource_fixture(&runtime, "(memory 4096)")
            .expect("256 MiB linear memory must remain available");
        let over_limit = instantiate_resource_fixture(&runtime, "(memory 4097)");
        assert!(
            over_limit.is_err(),
            "linear memory above 256 MiB must be rejected"
        );
    }

    #[test]
    fn table_element_limit_accepts_boundary_and_rejects_one_over() {
        let runtime = WasmRuntime::new().unwrap();

        instantiate_resource_fixture(&runtime, "(table 100000 funcref)")
            .expect("100,000 table elements must remain available");
        assert!(
            instantiate_resource_fixture(&runtime, "(table 100001 funcref)").is_err(),
            "table element counts above 100,000 must be rejected"
        );
    }

    #[test]
    fn table_count_limit_accepts_eight_and_rejects_nine() {
        let runtime = WasmRuntime::new().unwrap();
        let at_limit = "(table 1 funcref)".repeat(8);
        let over_limit = "(table 1 funcref)".repeat(9);

        instantiate_resource_fixture(&runtime, &at_limit)
            .expect("eight tables must remain available");
        assert!(
            instantiate_resource_fixture(&runtime, &over_limit).is_err(),
            "a ninth table must be rejected"
        );
    }

    #[test]
    fn memory_count_limit_accepts_four_and_rejects_five() {
        let runtime = WasmRuntime::new().unwrap();
        let at_limit = "(memory 1)".repeat(4);
        let over_limit = "(memory 1)".repeat(5);

        instantiate_resource_fixture(&runtime, &at_limit)
            .expect("four memories must remain available");
        assert!(
            instantiate_resource_fixture(&runtime, &over_limit).is_err(),
            "a fifth memory must be rejected"
        );
    }

    #[test]
    fn core_instance_limit_accepts_compatibility_boundary_and_rejects_one_over() {
        let runtime = WasmRuntime::new().unwrap();
        instantiate_core_instance_fixture(&runtime, crate::host_functions::MAX_CORE_INSTANCES)
            .expect("the compatibility-safe core-instance boundary must remain available");
        assert!(
            instantiate_core_instance_fixture(
                &runtime,
                crate::host_functions::MAX_CORE_INSTANCES + 1
            )
            .is_err(),
            "a core instance above the compatibility boundary must be rejected"
        );
    }

    #[test]
    fn locked_wasmtime_resource_count_causes_are_redacted_quota_errors() {
        let runtime = WasmRuntime::new().unwrap();
        let instance = instantiate_core_instance_fixture(
            &runtime,
            crate::host_functions::MAX_CORE_INSTANCES + 1,
        )
        .unwrap_err();
        let memory = instantiate_resource_fixture(&runtime, &"(memory 1)".repeat(5)).unwrap_err();
        let table =
            instantiate_resource_fixture(&runtime, &"(table 1 funcref)".repeat(9)).unwrap_err();

        assert_eq!(
            instance.root_cause().to_string(),
            "resource limit exceeded: instance count too high at 33"
        );
        assert_eq!(
            memory.root_cause().to_string(),
            "resource limit exceeded: memory count too high at 5"
        );
        assert_eq!(
            table.root_cause().to_string(),
            "resource limit exceeded: table count too high at 9"
        );
        assert_eq!(
            resource_quota_reason(&instance),
            Some("plugin instance quota exceeded")
        );
        assert_eq!(
            resource_quota_reason(&memory),
            Some("plugin memory quota exceeded")
        );
        assert_eq!(
            resource_quota_reason(&table),
            Some("plugin table quota exceeded")
        );
    }

    #[test]
    fn resource_count_errors_are_redacted_in_both_plugin_instantiation_modes() {
        let runtime = WasmRuntime::new().unwrap();
        let base = include_bytes!(concat!(
            env!("CARGO_MANIFEST_DIR"),
            "/../../plugins/ui-demo/ui-demo.wasm"
        ));
        const EMPTY_CORE_MODULE: &[u8] = b"\0asm\x01\0\0\0";
        // ui-demo already owns one linear memory and two tables. These modules
        // take the real plugin to Wasmtime's first rejected totals (5 and 9).
        const FOUR_MEMORY_CORE_MODULE: &[u8] =
            b"\0asm\x01\0\0\0\x05\x09\x04\0\x01\0\x01\0\x01\0\x01";
        const SEVEN_TABLE_CORE_MODULE: &[u8] = b"\0asm\x01\0\0\0\x04\x16\x07\x70\0\x01\x70\0\x01\x70\0\x01\x70\0\x01\x70\0\x01\x70\0\x01\x70\0\x01";
        let fixtures = [
            (
                "instance-count",
                plugin_with_extra_core_instances(
                    base,
                    EMPTY_CORE_MODULE,
                    crate::host_functions::MAX_CORE_INSTANCES + 1,
                ),
                "plugin instance quota exceeded",
            ),
            (
                "memory-count",
                plugin_with_extra_core_instances(base, FOUR_MEMORY_CORE_MODULE, 1),
                "plugin memory quota exceeded",
            ),
            (
                "table-count",
                plugin_with_extra_core_instances(base, SEVEN_TABLE_CORE_MODULE, 1),
                "plugin table quota exceeded",
            ),
        ];
        let plugin_log_dir = tempfile::tempdir().unwrap();

        for (id, bytes, expected) in fixtures {
            let loaded = loaded_binary_fixture(&runtime, id, &bytes);
            assert_unavailable_reason(
                loaded.instantiate_with_plugin_log_dir(
                    vec![],
                    10,
                    None,
                    HashMap::new(),
                    None,
                    plugin_log_dir.path(),
                ),
                expected,
            );
            assert_unavailable_reason(loaded.instantiate_for_metadata_validation(), expected);
        }
    }

    #[test]
    fn bundled_components_instantiate_with_the_compatibility_safe_core_instance_limit() {
        let runtime = WasmRuntime::new().unwrap();
        let plugin_log_dir = tempfile::tempdir().unwrap();
        for (id, bytes) in [
            (
                "ui-demo",
                include_bytes!(concat!(
                    env!("CARGO_MANIFEST_DIR"),
                    "/../../plugins/ui-demo/ui-demo.wasm"
                ))
                .as_slice(),
            ),
            (
                "malicious-metadata",
                include_bytes!(concat!(
                    env!("CARGO_MANIFEST_DIR"),
                    "/tests/fixtures/malicious-metadata/malicious-metadata.wasm"
                ))
                .as_slice(),
            ),
        ] {
            let loaded = runtime
                .load_module_from_bytes(id.to_string(), bytes)
                .unwrap();
            loaded
                .instantiate_with_plugin_log_dir(
                    vec![],
                    10,
                    None,
                    HashMap::new(),
                    None,
                    plugin_log_dir.path(),
                )
                .unwrap_or_else(|error| {
                    panic!("{id} must instantiate normally under all quotas: {error}")
                });
            let mut instance = loaded
                .instantiate_for_metadata_validation()
                .unwrap_or_else(|error| panic!("{id} must fit the core-instance quota: {error}"));
            instance
                .get_metadata()
                .unwrap_or_else(|error| panic!("{id} metadata must execute under quotas: {error}"));
        }
    }

    #[test]
    fn runtime_drop_stops_and_joins_epoch_ticker() {
        let runtime = WasmRuntime::new().unwrap();
        let ticker_exited = runtime.epoch_ticker_exit_probe();

        drop(runtime);

        assert!(
            ticker_exited.load(std::sync::atomic::Ordering::Acquire),
            "runtime Drop must join the epoch ticker before returning"
        );
    }

    #[test]
    fn infinite_component_becomes_terminal_and_second_call_never_reenters_guest() {
        let (outcome_tx, outcome_rx) = std::sync::mpsc::sync_channel(1);
        std::thread::spawn(move || {
            let outcome = (|| -> anyhow::Result<(PluginError, PluginError, i32, Duration)> {
                let runtime = WasmRuntime::new()?;
                let component = Component::new(
                    &runtime.engine,
                    r#"
                        (component
                            (core module $fixture
                                (func (export "run")
                                    (loop $spin (br $spin))))
                            (core instance $instance (instantiate $fixture))
                            (func (export "run")
                                (canon lift (core func $instance "run"))))
                    "#,
                )?;
                let host = HostFunctions::new_for_metadata_validation("terminal-test".to_string())?;
                let mut store = new_plugin_store(&runtime.engine, host)?;
                let instance = Linker::new(&runtime.engine).instantiate(&mut store, &component)?;
                let run = instance.get_typed_func::<(), ()>(&mut store, "run")?;
                let mut availability = InstanceAvailability::default();
                let call_entries = Arc::new(std::sync::atomic::AtomicUsize::new(0));

                let first_entries = call_entries.clone();
                let first = call_with_quotas(
                    &mut store,
                    &mut availability,
                    |store| {
                        first_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                        run.call(store, ())
                    },
                    |_| Ok(()),
                    PluginError::ExecutionError,
                )
                .unwrap_err();

                let second_started = std::time::Instant::now();
                let second_entries = call_entries.clone();
                let second = call_with_quotas(
                    &mut store,
                    &mut availability,
                    |store| {
                        second_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                        run.call(store, ())
                    },
                    |_| Ok(()),
                    PluginError::ExecutionError,
                )
                .unwrap_err();
                let second_elapsed = second_started.elapsed();
                let guest_entries = call_entries.load(std::sync::atomic::Ordering::SeqCst) as i32;
                Ok((first, second, guest_entries, second_elapsed))
            })();
            let _ = outcome_tx.send(outcome);
        });

        let (first, second, guest_entries, second_elapsed) = outcome_rx
            .recv_timeout(Duration::from_secs(2))
            .expect("infinite guest call must terminate under a wall-clock guard")
            .unwrap();
        assert!(matches!(first, PluginError::Unavailable(_)));
        assert!(matches!(second, PluginError::Unavailable(_)));
        assert_eq!(
            guest_entries, 1,
            "the terminal call must not enter the guest"
        );
        assert!(
            second_elapsed < Duration::from_millis(10),
            "terminal calls must fail before crossing the Wasm boundary"
        );
    }

    #[test]
    fn ordinary_guest_error_does_not_make_instance_terminal() {
        let runtime = WasmRuntime::new().unwrap();
        let host =
            HostFunctions::new_for_metadata_validation("ordinary-error".to_string()).unwrap();
        let mut store = new_plugin_store(&runtime.engine, host).unwrap();
        let mut availability = InstanceAvailability::default();
        let call_entries = std::sync::atomic::AtomicUsize::new(0);

        let first = call_with_quotas(
            &mut store,
            &mut availability,
            |_| -> wasmtime::Result<()> {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                Err(wasmtime::Error::msg("guest-owned secret"))
            },
            |_| Ok(()),
            PluginError::ExecutionError,
        )
        .unwrap_err();
        let second = call_with_quotas(
            &mut store,
            &mut availability,
            |_| {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                Ok(())
            },
            |_| Ok(()),
            PluginError::ExecutionError,
        );

        assert!(
            matches!(first, PluginError::ExecutionError(message) if message == "guest-owned secret")
        );
        assert!(second.is_ok());
        assert_eq!(call_entries.load(std::sync::atomic::Ordering::SeqCst), 2);
        assert_eq!(availability.reason(), None);
    }

    #[test]
    fn oversized_result_is_terminal_redacted_and_second_call_skips_guest_boundary() {
        let runtime = WasmRuntime::new().unwrap();
        let host = HostFunctions::new_for_metadata_validation("result-quota".to_string()).unwrap();
        let mut store = new_plugin_store(&runtime.engine, host).unwrap();
        let mut availability = InstanceAvailability::default();
        let call_entries = std::sync::atomic::AtomicUsize::new(0);
        let secret = "guest-secret";

        let first = call_with_quotas(
            &mut store,
            &mut availability,
            |_| {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                Ok(format!(
                    "{secret}{}",
                    "x".repeat(MAX_SERIALIZED_RESULT_BYTES)
                ))
            },
            validate_serialized_result,
            PluginError::ExecutionError,
        )
        .unwrap_err();
        let second = call_with_quotas(
            &mut store,
            &mut availability,
            |_| {
                call_entries.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
                Ok(String::new())
            },
            validate_serialized_result,
            PluginError::ExecutionError,
        )
        .unwrap_err();

        assert!(
            matches!(first, PluginError::Unavailable(ref reason) if reason == "plugin result quota exceeded" && !reason.contains(secret))
        );
        assert!(matches!(second, PluginError::Unavailable(_)));
        assert_eq!(call_entries.load(std::sync::atomic::Ordering::SeqCst), 1);
        assert_eq!(availability.reason(), Some("plugin result quota exceeded"));
    }
}
