//! Host functions that plugins can call
//!
//! This module implements the host-side functions that are exposed to WASM plugins
//! via the WASI Component Model.

mod archive;
mod http;
mod logging;
mod metadata;
mod settings;

use crate::arclain::plugin::host::{Host, LogLevel};
use crate::types::PluginCapability;
use arclain_core::ArchiveBackend;
use parking_lot::Mutex;
use std::collections::HashMap;
use std::sync::Arc;
use wasmtime::component::ResourceTable;
use wasmtime_wasi::{WasiCtx, WasiCtxBuilder, WasiView};

pub use http::{HttpClient, RateLimiter};

/// State for host functions
pub struct HostFunctions {
    pub http_client: Option<HttpClient>,
    pub capabilities: std::collections::HashSet<PluginCapability>,
    pub archive_backend: Option<Arc<dyn ArchiveBackend>>,
    pub current_archive: Arc<Mutex<Option<String>>>,
    pub current_password: Arc<Mutex<Option<String>>>,
    pub settings: Arc<Mutex<HashMap<String, String>>>,
    pub pending_messages: Arc<Mutex<Vec<(String, String)>>>,
    pub emitted_metadata: Arc<Mutex<Option<String>>>,
    pub network_log: Arc<Mutex<Vec<(std::time::SystemTime, String)>>>,
    pub metadata_cache: Option<Arc<arclain_db::MetadataCache>>,
    pub table: ResourceTable,
    pub ctx: WasiCtx,
}

impl HostFunctions {
    pub fn new(
        capabilities: std::collections::HashSet<PluginCapability>,
        requests_per_minute: u32,
        initial_settings: HashMap<String, String>,
    ) -> Self {
        let http_client = if capabilities.contains(&PluginCapability::Network) {
            Some(HttpClient::new(requests_per_minute))
        } else {
            None
        };

        // Initialize WASI context
        let ctx = WasiCtxBuilder::new().inherit_stdio().inherit_args().build();

        Self {
            http_client,
            capabilities,
            archive_backend: None,
            current_archive: Arc::new(Mutex::new(None)),
            current_password: Arc::new(Mutex::new(None)),
            settings: Arc::new(Mutex::new(initial_settings)),
            pending_messages: Arc::new(Mutex::new(Vec::new())),
            emitted_metadata: Arc::new(Mutex::new(None)),
            network_log: Arc::new(Mutex::new(Vec::new())),
            metadata_cache: None,
            table: ResourceTable::new(),
            ctx,
        }
    }

    pub fn with_backend(
        capabilities: std::collections::HashSet<PluginCapability>,
        requests_per_minute: u32,
        backend: Arc<dyn ArchiveBackend>,
        initial_settings: HashMap<String, String>,
    ) -> Self {
        let mut host_funcs = Self::new(capabilities, requests_per_minute, initial_settings);
        host_funcs.archive_backend = Some(backend);
        host_funcs
    }

    pub fn set_metadata_cache(&mut self, cache: Arc<arclain_db::MetadataCache>) {
        self.metadata_cache = Some(cache);
    }

    pub fn set_archive_context(&self, archive_path: Option<String>, password: Option<String>) {
        *self.current_archive.lock() = archive_path;
        *self.current_password.lock() = password;
    }

    pub fn check_capability(&self, cap: PluginCapability) -> bool {
        self.capabilities.contains(&cap)
    }
}

// Implement WasiView for HostFunctions
impl WasiView for HostFunctions {
    fn table(&mut self) -> &mut ResourceTable {
        &mut self.table
    }

    fn ctx(&mut self) -> &mut WasiCtx {
        &mut self.ctx
    }
}

// Implement the Host trait generated by wit-bindgen
impl Host for HostFunctions {
    fn log(&mut self, level: LogLevel, message: String) {
        self.impl_log(level, message)
    }

    fn log_network_activity(&mut self, message: String) {
        self.impl_log_network_activity(message)
    }

    fn get_setting(&mut self, key: String) -> Option<String> {
        self.impl_get_setting(key)
    }

    fn set_setting(&mut self, key: String, value: String) {
        self.impl_set_setting(key, value)
    }

    fn http_get(&mut self, url: String) -> std::result::Result<String, String> {
        self.impl_http_get(url)
    }

    fn http_post(&mut self, url: String, body: String) -> std::result::Result<String, String> {
        self.impl_http_post(url, body)
    }

    fn file_read(&mut self, archive: String, file: String) -> std::result::Result<String, String> {
        self.impl_file_read(archive, file)
    }

    fn file_write(
        &mut self,
        archive: String,
        file: String,
        data: String,
    ) -> std::result::Result<String, String> {
        self.impl_file_write(archive, file, data)
    }

    fn current_archive_info(&mut self) -> Option<crate::arclain::plugin::host::ArchiveInfo> {
        self.impl_current_archive_info()
    }

    fn list_archive_files(&mut self) -> std::result::Result<Vec<String>, String> {
        self.impl_list_archive_files()
    }

    fn emit_metadata(&mut self, metadata_json: String) {
        self.impl_emit_metadata(metadata_json)
    }

    fn show_message(&mut self, title: String, message: String) {
        self.impl_show_message(title, message)
    }

    fn get_cached_metadata(&mut self, id: String) -> Option<String> {
        self.impl_get_cached_metadata(id)
    }

    fn save_cached_metadata(&mut self, id: String, json: String) {
        self.impl_save_cached_metadata(id, json)
    }
}

// Implement the ui::Host trait (empty - ui interface only defines types)
impl crate::arclain::plugin::ui::Host for HostFunctions {}

// Implement the rules::Host trait (empty - rules interface only defines types)
impl crate::arclain::plugin::rules::Host for HostFunctions {}
