use std::fmt::Write as _;
use std::path::PathBuf;
use wit_parser::{Function, FunctionKind, InterfaceId, Resolve, Type, TypeDefKind, TypeId};

const CANONICAL_WIT: &str = include_str!("../../wirt-sdk/wit/plugin.wit");
const CHECKED_SCHEMA: &str = include_str!("src/wirt_schema.rs");
const CANONICAL_INTERFACES: [&str; 4] = ["host", "meta", "rules", "ui"];

fn main() {
    println!("cargo:rerun-if-changed=../../wirt-sdk/wit/plugin.wit");
    println!("cargo:rerun-if-changed=src/wirt_schema.rs");

    let generated = generate_schema().unwrap_or_else(|error| {
        panic!("failed to derive the Wirt interface schema from canonical WIT: {error}")
    });
    if CHECKED_SCHEMA != generated {
        let output = PathBuf::from(std::env::var_os("OUT_DIR").expect("OUT_DIR is set"))
            .join("wirt_schema.rs");
        std::fs::write(&output, generated)
            .expect("generated Wirt schema can be written to OUT_DIR");
        panic!(
            "src/wirt_schema.rs is stale; replace it with the mechanically generated projection at {}",
            output.display()
        );
    }
}

fn generate_schema() -> Result<String, String> {
    let mut resolve = Resolve::default();
    let package_id = resolve
        .push_str("wirt-sdk/wit/plugin.wit", CANONICAL_WIT)
        .map_err(|error| error.to_string())?;
    let package = &resolve.packages[package_id];
    let mut actual = package
        .interfaces
        .keys()
        .map(String::as_str)
        .collect::<Vec<_>>();
    actual.sort_unstable();
    if actual != CANONICAL_INTERFACES {
        return Err(format!(
            "expected exactly the canonical interfaces {CANONICAL_INTERFACES:?}, found {actual:?}"
        ));
    }

    let mut output = String::from(
        "// @generated by crates/wirt/build.rs from wirt-sdk/wit/plugin.wit.\n\
         // Do not edit by hand; a stale projection fails the Wirt build.\n\n\
         const CANONICAL_WIRT_INTERFACES: &[CanonicalInterface] = &[\n",
    );
    for name in CANONICAL_INTERFACES {
        let interface_id = package.interfaces[name];
        let interface = &resolve.interfaces[interface_id];
        let mut members = interface
            .types
            .iter()
            .map(|(name, id)| {
                render_type_definition(&resolve, interface_id, *id, 0)
                    .map(|signature| (name.as_str(), format!("type:{signature}")))
            })
            .chain(interface.functions.iter().map(|(name, function)| {
                render_function(&resolve, interface_id, function, 0)
                    .map(|signature| (name.as_str(), signature))
            }))
            .collect::<Result<Vec<_>, _>>()?;
        members.sort_by(|left, right| left.0.cmp(right.0));

        writeln!(
            output,
            "    CanonicalInterface {{ name: {:?}, members: &[",
            resolve
                .id_of(interface_id)
                .ok_or("canonical interface has no id")?
        )
        .unwrap();
        for (member, signature) in members {
            writeln!(
                output,
                "        CanonicalMember {{ name: {member:?}, signature: {signature:?} }},"
            )
            .unwrap();
        }
        output.push_str("    ] },\n");
    }
    output.push_str("];\n");
    Ok(output)
}

fn render_function(
    resolve: &Resolve,
    interface: InterfaceId,
    function: &Function,
    depth: usize,
) -> Result<String, String> {
    if depth > 64 {
        return Err("canonical WIT type nesting exceeds 64 levels".to_owned());
    }
    let mode = match function.kind {
        FunctionKind::Freestanding => "sync",
        FunctionKind::AsyncFreestanding => "async",
        _ => return Err("resource methods require an explicit schema renderer update".to_owned()),
    };
    let mut output = format!("func:{mode}(");
    for (index, parameter) in function.params.iter().enumerate() {
        if index > 0 {
            output.push(',');
        }
        write!(output, "{}=", parameter.name).unwrap();
        output.push_str(&render_type(resolve, interface, parameter.ty, depth + 1)?);
    }
    output.push_str(")->");
    match function.result {
        Some(ty) => output.push_str(&render_type(resolve, interface, ty, depth + 1)?),
        None => output.push_str("none"),
    }
    Ok(output)
}

fn render_type(
    resolve: &Resolve,
    interface: InterfaceId,
    ty: Type,
    depth: usize,
) -> Result<String, String> {
    let primitive = match ty {
        Type::Bool => Some("bool"),
        Type::U8 => Some("u8"),
        Type::U16 => Some("u16"),
        Type::U32 => Some("u32"),
        Type::U64 => Some("u64"),
        Type::S8 => Some("s8"),
        Type::S16 => Some("s16"),
        Type::S32 => Some("s32"),
        Type::S64 => Some("s64"),
        Type::F32 => Some("f32"),
        Type::F64 => Some("f64"),
        Type::Char => Some("char"),
        Type::String => Some("string"),
        Type::ErrorContext => Some("error-context"),
        Type::Id(id) => return render_type_definition(resolve, interface, id, depth + 1),
    };
    Ok(primitive
        .expect("all primitive WIT types are covered")
        .to_owned())
}

fn render_type_definition(
    resolve: &Resolve,
    interface: InterfaceId,
    id: TypeId,
    depth: usize,
) -> Result<String, String> {
    if depth > 64 {
        return Err("canonical WIT type nesting exceeds 64 levels".to_owned());
    }
    let definition = &resolve.types[id];
    let nested = |ty| render_type(resolve, interface, ty, depth + 1);
    match &definition.kind {
        TypeDefKind::Record(record) => {
            let mut output = String::from("record(");
            for (index, field) in record.fields.iter().enumerate() {
                if index > 0 {
                    output.push(',');
                }
                write!(output, "{}=", field.name).unwrap();
                output.push_str(&nested(field.ty)?);
            }
            output.push(')');
            Ok(output)
        }
        TypeDefKind::Resource | TypeDefKind::Handle(_) => Err(
            "Wirt resources require an identity-aware schema comparator before entering the ABI"
                .to_owned(),
        ),
        TypeDefKind::Flags(flags) => Ok(format!(
            "flags({})",
            flags
                .flags
                .iter()
                .map(|flag| flag.name.as_str())
                .collect::<Vec<_>>()
                .join(",")
        )),
        TypeDefKind::Tuple(tuple) => Ok(format!(
            "tuple({})",
            tuple
                .types
                .iter()
                .map(|ty| nested(*ty))
                .collect::<Result<Vec<_>, _>>()?
                .join(",")
        )),
        TypeDefKind::Variant(variant) => {
            let mut output = String::from("variant(");
            for (index, case) in variant.cases.iter().enumerate() {
                if index > 0 {
                    output.push(',');
                }
                write!(output, "{}=", case.name).unwrap();
                match case.ty {
                    Some(ty) => output.push_str(&nested(ty)?),
                    None => output.push_str("none"),
                }
            }
            output.push(')');
            Ok(output)
        }
        TypeDefKind::Enum(cases) => Ok(format!(
            "enum({})",
            cases
                .cases
                .iter()
                .map(|case| case.name.as_str())
                .collect::<Vec<_>>()
                .join(",")
        )),
        TypeDefKind::Option(ty) => Ok(format!("option({})", nested(*ty)?)),
        TypeDefKind::Result(result) => Ok(format!(
            "result({},{})",
            render_optional_type(resolve, interface, result.ok, depth + 1)?,
            render_optional_type(resolve, interface, result.err, depth + 1)?
        )),
        TypeDefKind::List(ty) => Ok(format!("list({})", nested(*ty)?)),
        TypeDefKind::Map(key, value) => Ok(format!("map({},{})", nested(*key)?, nested(*value)?)),
        TypeDefKind::FixedLengthList(ty, length) => {
            Ok(format!("fixed-list({length},{})", nested(*ty)?))
        }
        TypeDefKind::Future(ty) => Ok(format!(
            "future({})",
            render_optional_type(resolve, interface, *ty, depth + 1)?
        )),
        TypeDefKind::Stream(ty) => Ok(format!(
            "stream({})",
            render_optional_type(resolve, interface, *ty, depth + 1)?
        )),
        TypeDefKind::Type(ty) => nested(*ty),
        TypeDefKind::Unknown => Err("resolved canonical WIT contains an unknown type".to_owned()),
    }
}

fn render_optional_type(
    resolve: &Resolve,
    interface: InterfaceId,
    ty: Option<Type>,
    depth: usize,
) -> Result<String, String> {
    match ty {
        Some(ty) => render_type(resolve, interface, ty, depth),
        None => Ok("none".to_owned()),
    }
}
