[package]
name = "wirt"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow.workspace = true
cap-fs-ext = "=4.0.2"
cap-std = "=4.0.2"
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
toml = "0.9.8"
tracing.workspace = true
wasmtime = { version = "=47.0.1", features = ["component-model", "cache"] }
wasmtime-wasi = "=47.0.1"
wasmparser.workspace = true
zip.workspace = true

[dev-dependencies]
tempfile.workspace = true
wasm-encoder = { version = "=0.252.0", default-features = false, features = ["std", "component-model", "wasmparser"] }
