// @generated - Diesel schema definitions
//
// This file defines all database tables for Diesel ORM.
// Normally generated by `diesel print-schema`, but maintained manually
// to avoid CLI dependency during development.

diesel::table! {
    /// Simple key-value configuration storage
    app_config (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::table! {
    /// Title text replacements for cleaning product names
    title_replacements (id) {
        id -> Integer,
        original -> Text,
        replacement -> Text,
        is_system -> Bool,
        created_at -> Text,
    }
}

diesel::table! {
    /// Rules for organizing archive contents
    organization_rules (id) {
        id -> Integer,
        name -> Text,
        description -> Nullable<Text>,
        category -> Text,
        priority -> Integer,
        is_enabled -> Bool,
        is_system -> Bool,
        trigger_json -> Text,
        actions_json -> Text,
        created_at -> Text,
        modified_at -> Nullable<Text>,
    }
}

diesel::table! {
    /// Plugin network domain whitelist entries
    domain_whitelist (id) {
        id -> Integer,
        plugin_id -> Text,
        domain -> Text,
        approved -> Bool,
        approved_at -> Nullable<Text>,
    }
}

diesel::table! {
    /// UI toolbar/context menu items
    ui_items (id) {
        id -> Text,
        region -> Text,
        group_id -> Nullable<Text>,
        label -> Text,
        icon -> Nullable<Text>,
        visible -> Bool,
        sort_order -> Integer,
        action_type -> Text,
        action_data -> Nullable<Text>,
        display_mode -> Text,
    }
}

diesel::table! {
    /// UI region settings (toolbar, context menu, etc.)
    ui_regions (id) {
        id -> Text,
        enabled -> Bool,
        global_display_mode -> Text,
    }
}

diesel::table! {
    /// UI display options key-value store
    ui_display_options (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::table! {
    /// Product metadata for library items
    product_metadata (id) {
        id -> Text,
        source -> Text,
        title -> Nullable<Text>,
        circle -> Nullable<Text>,
        release_date -> Nullable<Text>,
        genres -> Nullable<Text>,
        description -> Nullable<Text>,
        cover_url -> Nullable<Text>,
        detail_url -> Nullable<Text>,
        json_blob -> Nullable<Text>,
        created_at -> Text,
        modified_at -> Nullable<Text>,
    }
}

diesel::table! {
    /// Product content blobs (covers, samples, etc.)
    product_content (id) {
        id -> Integer,
        product_id -> Text,
        content_type -> Text,
        content_index -> Integer,
        content_hash -> Text,
        source_url -> Nullable<Text>,
        width -> Nullable<Integer>,
        height -> Nullable<Integer>,
        size_bytes -> Nullable<BigInt>,
        cached_at -> BigInt,
    }
}

diesel::table! {
    /// Checksum configuration settings
    checksum_settings (key) {
        key -> Text,
        value -> Text,
    }
}

diesel::table! {
    /// File checksum records
    file_checksums (id) {
        id -> Integer,
        path -> Text,
        archive_id -> Text,
        hash -> Text,
        size -> BigInt,
        mtime -> BigInt,
        algorithm -> Text,
        computed_at -> Text,
    }
}

diesel::table! {
    /// Merkle tree roots for archive verification
    merkle_roots (archive_id) {
        archive_id -> Text,
        root_hash -> Text,
        algorithm -> Text,
        computed_at -> Text,
    }
}

diesel::table! {
    /// Checksum operation tracking
    checksum_operations (id) {
        id -> Integer,
        archive_id -> Text,
        op_type -> Text,
        state -> Text,
        started_at -> Text,
        completed_at -> Nullable<Text>,
        error_message -> Nullable<Text>,
    }
}

diesel::table! {
    /// Cache index for tracking cached data
    cache_index (id) {
        id -> Integer,
        key -> Text,
        product_id -> Nullable<Text>,
        content_hash -> Text,
        source_url -> Nullable<Text>,
        cache_type -> Text,
        created_at -> Text,
        last_accessed -> Nullable<Text>,
        size_bytes -> Nullable<BigInt>,
    }
}

diesel::table! {
    /// User configuration (singleton table)
    user_config (id) {
        id -> Integer,
        vault_path -> Nullable<Text>,
        cache_directory -> Nullable<Text>,
        last_opened_archive -> Nullable<Text>,
        created_at -> Text,
        modified_at -> Nullable<Text>,
    }
}

// Allow joining tables if needed in the future
diesel::allow_tables_to_appear_in_same_query!(
    app_config,
    title_replacements,
    organization_rules,
    domain_whitelist,
    ui_items,
    ui_regions,
    ui_display_options,
    product_metadata,
    product_content,
    checksum_settings,
    file_checksums,
    merkle_roots,
    checksum_operations,
    cache_index,
    user_config,
);
