use anyhow::Result;
use rusqlite::{Connection, OptionalExtension};

mod sqlite_db;
pub use sqlite_db::SqliteDb;

/// redb K/V wrapper. Internal plumbing for the secrets store —
/// `SecretsDb` is the only intended consumer. Demoted from the public
/// re-export (`pub use redb_wrapper::ReDb`) per
/// docs/audits/2026-05-19-dependencies.md §3 + §5 medium #7: the type
/// has no external users and exposing it broadened the public surface
/// without buying anything. `secrets_db.rs` references it via
/// `crate::redb_wrapper::ReDb` directly; module visibility is enough.
mod redb_wrapper;

// Diesel schema definitions (generated by diesel CLI or manually
// maintained). Internal plumbing: consumers should call the typed CRUD
// helpers (`save_profile`, `get_cache_entry`, etc.), not run raw Diesel
// against the tables. Demoting to `pub(crate)` prevents the dual-CRUD
// collapse (Wave 3) from being undone by a downstream module rolling
// its own `schema::*::dsl::*` query.
pub(crate) mod diesel_schema;

// Connection pool for Diesel
mod pool;
pub use pool::{DbConn, DbPool, DieselPool};

mod config;
pub use config::{
    delete_title_replacement, get_title_filter_settings, list_title_replacements,
    save_title_filter_settings, save_title_replacement, ConfigDb, DbTitleFilterSettings,
    DbTitleReplacement, NewTitleReplacement,
};

pub mod cache;

pub use cache::{
    clear_all_entries, delete_all_search_cache, delete_by_pattern, delete_cache_entry,
    delete_old_search_cache, delete_orphaned_entries, get_all_content_hashes, get_cache_entry,
    get_cache_stats, get_entries_by_product, has_cache_entry, migrate_fix_entries,
    touch_cache_entry, upsert_cache_entry, CacheDb, CacheEntry, CacheStats, CacheType,
};

mod secrets;
pub use secrets::{PassRule as DbPassRule, SecretMutation, SecretsDb};

mod metadata_store;
pub use metadata_store::MetadataStore;

mod organization;
pub use organization::{
    delete_rule, get_rule, list_rules, save_rule, DbOrganizationRule, DbOrganizationRuleRow,
};

mod archive_profiles;
pub use archive_profiles::{
    delete_profile, get_default_profile, get_profile, list_profiles, save_profile,
    set_default_profile, DbArchiveProfile, DbArchiveProfileRow,
};

mod checksum;
pub use checksum::{
    begin_checksum_operation, delete_checksum_operation, get_checksum_algorithm, get_checksum_mode,
    get_file_checksum, get_merkle_root, get_pending_checksum_operations, set_checksum_algorithm,
    set_checksum_mode, store_file_checksum, store_merkle_root, update_checksum_operation,
    ChecksumDb, DbFileChecksum, DbOperation, OpId, OpState, OpType, VerifyMode,
};

mod user_config;
pub use user_config::UserConfig;

mod ui;
pub use ui::{
    delete_item, ensure_ui_tables, get_display_option, list_items_by_region,
    seed_defaults_if_empty, set_display_option, set_display_options, sync_host_item, upsert_item,
    ActionType, DisplayMode, UiItem, UiRegion, UiRegionConfig,
};

mod domain_whitelist;
pub use domain_whitelist::{
    approve_domain, delete_plugin_whitelist, delete_whitelist_entry, domain_exists,
    ensure_whitelist_table, is_domain_approved, list_pending_approvals, list_plugin_domains,
    list_whitelist_entries, revoke_domain, upsert_whitelist_entry, DbWhitelistEntry,
    DbWhitelistRow,
};

pub mod library;

/// Pipeline execution history — records each pipeline run against its input
/// and pipeline-config hashes, enabling idempotent re-runs and crash recovery.
pub mod pipeline_runs;
pub use library::{
    delete_product_content, get_all_content, get_cover, get_screenshots, save_product_content,
    CompletenessScore, ContentType, MetadataSource, ProductContent, ProductMetadata,
};
pub use pipeline_runs::{
    begin_pipeline_run, ensure_pipeline_runs_table, find_completed_run, flag_stale_in_progress,
    list_interrupted_since, mark_run_completed, mark_run_failed,
    output_kind as pipeline_output_kind, status as pipeline_run_status, DbPipelineRun,
    NewPipelineRun, INTERRUPTED_MARKER,
};

/// Re-export Connection so dependents don't need rusqlite directly.
pub use rusqlite::Connection as DbConnection;

/// Re-export Diesel connection type
pub use diesel::SqliteConnection;

mod bootstrap;
mod secrets_key;

pub use bootstrap::{open_databases, ConfigDbs, DbPaths};
pub use secrets_key::SecretsKey;

/// Simple K/V config helpers (stored in plain `app_config` table).
///
/// Strategy (b) survival of the dual-CRUD collapse (see
/// `docs/audits/2026-05-19-dependencies.md` §5 #6): both
/// `get_config` (rusqlite) and `get_config_diesel` below are kept
/// because each has live callers that cannot easily switch sides.
/// Rusqlite path is used by the early-boot vault/secrets bootstrap
/// (see `core::services::secrets_service` and
/// `ui::core::state::vault_ops`), which runs before the Diesel pool
/// exists. The Diesel mirror is used by `core::services::config_service`
/// and `crate::config::get_title_filter_settings` once the pool is up.
pub fn get_config(conn: &Connection, key: &str) -> Result<Option<String>> {
    let mut stmt = conn.prepare("SELECT value FROM app_config WHERE key = ?1")?;
    let val = stmt
        .query_row([key], |row| row.get::<_, String>(0))
        .optional()?;
    Ok(val)
}

pub fn set_config(conn: &Connection, key: &str, value: &str) -> Result<()> {
    conn.execute(
        "INSERT INTO app_config(key, value) VALUES(?1, ?2) \
         ON CONFLICT(key) DO UPDATE SET value = excluded.value",
        (key, value),
    )?;
    Ok(())
}

// ============================================================================
// Diesel-based config helpers (cleaner DSL syntax)
// ============================================================================

use diesel::prelude::*;
use diesel::result::OptionalExtension as DieselOptionalExtension;

/// Diesel-based get_config - true DSL, no string formatting
pub fn get_config_diesel(
    conn: &mut diesel::SqliteConnection,
    key_param: &str,
) -> Result<Option<String>> {
    use diesel_schema::app_config::dsl::*;

    let result = app_config
        .filter(key.eq(key_param))
        .select(value)
        .first::<String>(conn)
        .optional() // This is diesel's optional from DieselOptionalExtension
        .map_err(diesel_err("query"))?;

    Ok(result)
}

/// Diesel-based set_config - true DSL upsert
pub fn set_config_diesel(conn: &mut diesel::SqliteConnection, k: &str, v: &str) -> Result<()> {
    use diesel_schema::app_config::dsl::*;

    diesel::insert_into(app_config)
        .values((key.eq(k), value.eq(v)))
        .on_conflict(key)
        .do_update()
        .set(value.eq(v))
        .execute(conn)
        .map_err(diesel_err("insert"))?;

    Ok(())
}

/// Helper that returns a `.map_err`-shaped closure wrapping a diesel
/// error in `anyhow::Error` with a "Diesel <op> failed: <err>" message.
///
/// Centralises the boilerplate that previously appeared at ~49 call
/// sites across 9 db modules. Use as
/// `query.execute(conn).map_err(diesel_err("insert"))?`.
pub(crate) fn diesel_err(op: &'static str) -> impl FnOnce(diesel::result::Error) -> anyhow::Error {
    move |e| anyhow::anyhow!("Diesel {} failed: {}", op, e)
}

#[cfg(test)]
mod tests;
