use anyhow::{anyhow, Context, Result};
use base64::engine::general_purpose::STANDARD as B64;
use base64::Engine;
use rusqlite::{Connection, OptionalExtension};
use std::fs;
use std::path::{Path, PathBuf};
use zeroize::Zeroizing;

#[cfg(unix)]
use std::os::unix::fs::PermissionsExt;

// SqliteDb comes from mini-orm (shared ORM crate)
pub use mini_orm::SqliteDb;

mod redb_wrapper;

pub use redb_wrapper::ReDb;

/// Legacy Rusqlite code
pub mod legacy;

// Diesel schema definitions (generated by diesel CLI or manually maintained)
pub mod diesel_schema;

// Connection pool for Diesel
mod pool;
pub use pool::{DbConn, DbPool, DieselPool};

mod config;
pub use config::{
    delete_title_replacement, delete_title_replacement_diesel, get_title_filter_settings,
    list_title_replacements, list_title_replacements_diesel, save_title_filter_settings,
    save_title_replacement, save_title_replacement_diesel, ConfigDb, DbTitleFilterSettings,
    DbTitleReplacement, NewTitleReplacement,
};

pub mod cache;

pub use cache::{
    clear_all_entries, delete_all_search_cache, delete_by_pattern, delete_cache_entry,
    delete_old_search_cache, delete_orphaned_entries, get_all_content_hashes, get_cache_entry,
    get_cache_stats, get_entries_by_product, has_cache_entry, migrate_fix_entries,
    touch_cache_entry, upsert_cache_entry, CacheDb, CacheEntry, CacheStats, CacheType,
};

mod secrets;
pub use secrets::{PassRule as DbPassRule, SecretsDb};

mod metadata_store;
pub use metadata_store::MetadataStore;

mod organization;
pub use organization::{
    delete_rule, delete_rule_diesel, get_rule, get_rule_diesel, list_rules, list_rules_diesel,
    save_rule, save_rule_diesel, DbOrganizationRule, DbOrganizationRuleRow,
};

mod archive_profiles;
pub use archive_profiles::{
    delete_profile, delete_profile_diesel, get_default_profile, get_default_profile_diesel,
    get_profile, get_profile_diesel, list_profiles, list_profiles_diesel, save_profile,
    save_profile_diesel, set_default_profile, set_default_profile_diesel, DbArchiveProfile,
    DbArchiveProfileRow,
};

mod checksum;
pub use checksum::{
    begin_checksum_operation, delete_checksum_operation, get_checksum_algorithm,
    get_checksum_algorithm_diesel, get_checksum_mode, get_checksum_mode_diesel, get_file_checksum,
    get_merkle_root, get_pending_checksum_operations, set_checksum_algorithm,
    set_checksum_algorithm_diesel, set_checksum_mode, set_checksum_mode_diesel,
    store_file_checksum, store_merkle_root, update_checksum_operation, ChecksumDb, DbFileChecksum,
    DbOperation, OpId, OpState, OpType, VerifyMode,
};
pub use mini_orm::{JoinType, OrderDirection, QueryBuilder};

/// Type-safe database schema definitions
pub mod schema;

/// Re-export derive macros from mini-orm
pub use mini_orm::{DbConfig, DbTable};

mod user_config;
pub use user_config::UserConfig;

mod ui;
pub use ui::{
    delete_item, delete_item_diesel, ensure_ui_tables, get_display_option,
    get_display_option_diesel, get_item, get_item_diesel, get_region_config, list_items_by_region,
    list_items_by_region_diesel, seed_defaults_if_empty, set_display_option,
    set_display_option_diesel, set_item_display_mode, set_item_order, set_item_visibility,
    set_item_visibility_diesel, upsert_item, upsert_item_diesel, upsert_region_config, ActionType,
    DisplayMode, UiItem, UiRegion, UiRegionConfig,
};

mod domain_whitelist;
pub use domain_whitelist::{
    approve_domain,
    approve_domain_diesel,
    delete_plugin_whitelist,
    delete_whitelist_entry,
    delete_whitelist_entry_diesel,
    domain_exists,
    ensure_whitelist_table,
    is_domain_approved,
    is_domain_approved_diesel,
    list_pending_approvals,
    list_plugin_domains,
    list_plugin_domains_diesel,
    list_whitelist_entries,
    // Diesel DSL versions
    list_whitelist_entries_diesel,
    revoke_domain,
    revoke_domain_diesel,
    upsert_whitelist_entry,
    DbWhitelistEntry,
    DbWhitelistRow,
};

pub mod library;

/// Pipeline execution history — records each pipeline run against its input
/// and pipeline-config hashes, enabling idempotent re-runs and crash recovery.
pub mod pipeline_runs;
pub use pipeline_runs::{
    begin_pipeline_run, ensure_pipeline_runs_table, find_completed_run, flag_stale_in_progress,
    list_interrupted_since, mark_run_completed, mark_run_failed, output_kind as pipeline_output_kind,
    status as pipeline_run_status, DbPipelineRun, NewPipelineRun, INTERRUPTED_MARKER,
};
pub use library::{
    delete_product_content,
    get_all_content,
    get_cover,
    get_screenshots,
    save_product_content,
    CompletenessScore,
    ContentType,
    MetadataSource,
    ProductContent,
    ProductMetadata,
};

/// Re-export Connection so dependents don't need rusqlite directly.
pub use rusqlite::Connection as DbConnection;

/// Re-export Diesel connection type
pub use diesel::SqliteConnection;

/// Canonical paths for the two databases and optional key-file
#[derive(Debug, Clone)]
pub struct DbPaths {
    pub config_db: PathBuf,
    pub cache_db: PathBuf,
    pub secrets_db: PathBuf,
    pub key_file: Option<PathBuf>,
}

impl DbPaths {
    /// Calculate default paths without creating them.
    /// Creation is now handled by arclain_core::dirs::AppDirectories.
    pub fn calculate_defaults(app_name: &str) -> Result<Self> {
        let base = dirs::config_dir()
            .unwrap_or_else(|| PathBuf::from("."))
            .join(app_name);

        let databases_dir = base.join("databases");
        let secrets_dir = base.join("secrets");

        Ok(Self {
            config_db: databases_dir.join("config.sqlite"),
            cache_db: databases_dir.join("metadata.sqlite"),
            secrets_db: secrets_dir.join("pass.redb"),
            key_file: Some(secrets_dir.join("master.key")),
        })
    }
}

/// Zeroizing in-memory holder for the 32-byte AES encryption key
pub struct SecretsKey(pub Zeroizing<Vec<u8>>);

// Custom Debug implementation to avoid logging key material
impl std::fmt::Debug for SecretsKey {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("SecretsKey")
            .field("len", &self.0.len())
            .field("data", &"[REDACTED]")
            .finish()
    }
}

impl SecretsKey {
    /// Generate a new random 32-byte key
    pub fn generate() -> Self {
        use rand::RngCore;
        let mut key = vec![0u8; 32];
        rand::thread_rng().fill_bytes(&mut key);
        Self(Zeroizing::new(key))
    }

    /// Save the key to a file in base64 format with secure permissions
    pub fn save_to_file(&self, path: &Path) -> Result<()> {
        // Validate path to prevent directory traversal
        validate_path(path)?;

        // Create parent directory if it doesn't exist
        if let Some(parent) = path.parent() {
            fs::create_dir_all(parent)
                .with_context(|| format!("creating directory {}", parent.display()))?;

            // Set directory permissions to 700 (user-only) on Unix
            #[cfg(unix)]
            {
                let perms = fs::Permissions::from_mode(0o700);
                fs::set_permissions(parent, perms)
                    .with_context(|| format!("setting permissions on {}", parent.display()))?;
            }
        }

        let encoded = B64.encode(&*self.0);
        fs::write(path, encoded).with_context(|| format!("writing key to {}", path.display()))?;

        // Set file permissions to 600 (read/write user only) on Unix
        #[cfg(unix)]
        {
            let perms = fs::Permissions::from_mode(0o600);
            fs::set_permissions(path, perms)
                .with_context(|| format!("setting permissions on {}", path.display()))?;
        }

        Ok(())
    }

    /// Load the key from a file
    pub fn load_from_file(path: &Path) -> Result<Self> {
        let contents = fs::read_to_string(path)
            .with_context(|| format!("reading key from {}", path.display()))?;
        let bytes = B64
            .decode(contents.trim())
            .context("Invalid base64 in key file")?;

        if bytes.len() != 32 {
            return Err(anyhow!("Invalid key length: expected 32 bytes"));
        }

        Ok(Self(Zeroizing::new(bytes)))
    }

    /// Get the 32-byte key as a fixed-size array
    pub fn as_bytes(&self) -> [u8; 32] {
        let mut arr = [0u8; 32];
        arr.copy_from_slice(&self.0);
        arr
    }

    /// Return hex string (for debugging/logging)
    pub fn as_hex_upper(&self) -> String {
        hex_encode_upper(&self.0)
    }
}

/// Validate that a path is safe (no parent traversal)
fn validate_path(path: &Path) -> Result<()> {
    for component in path.components() {
        if matches!(component, std::path::Component::ParentDir) {
            return Err(anyhow!("Invalid path: contains parent directory traversal"));
        }
    }
    Ok(())
}

/// Holds open connections to both databases
pub struct ConfigDbs {
    pub config: SqliteDb,
    pub secrets: SecretsDb,
    pub metadata: MetadataStore,
    pub config_pool: DieselPool,
    pub cache_pool: DieselPool,
}

/// Open all databases, initializing schemas if needed
pub fn open_databases(paths: &DbPaths, key: &SecretsKey) -> Result<ConfigDbs> {
    // Open config database using new module
    let config_db = ConfigDb::open(&paths.config_db)
        .with_context(|| format!("Failed to open config database at {:?}", paths.config_db))?;

    // Create Diesel pool for config
    let config_pool = DieselPool::new(&paths.config_db)
        .with_context(|| "Failed to create config database pool")?;

    // Ensure cache directory exists - REMOVED (Handled by AppDirectories)
    // if let Some(parent) = paths.cache_db.parent() {
    //     std::fs::create_dir_all(parent)
    //         .with_context(|| format!("Failed to create cache directory at {:?}", parent))?;
    // }

    // Open cache database
    let cache_db = CacheDb::open(&paths.cache_db)
        .with_context(|| format!("Failed to open cache database at {:?}", paths.cache_db))?;

    // Create Diesel pool for cache
    let cache_pool =
        DieselPool::new(&paths.cache_db).with_context(|| "Failed to create cache database pool")?;

    // Open secrets database using new module
    let secrets_db = SecretsDb::open(&paths.secrets_db, &key.as_bytes())
        .with_context(|| format!("Failed to open secrets database at {:?}", paths.secrets_db))?;

    Ok(ConfigDbs {
        config: config_db.into_sqlite_db(),
        secrets: secrets_db,
        metadata: MetadataStore::new(
            cache_db.into_sqlite_db(),
            cache_pool.clone(),
            paths
                .cache_db
                .parent()
                .unwrap_or(Path::new("."))
                .join("metadata"),
            Some(paths.cache_db.clone()),
        ),
        config_pool,
        cache_pool,
    })
}

/// Simple K/V config helpers (stored in plain config.sqlite)
/// Uses schema::AppConfig with ParamExpr for type-safe parameterized queries
pub fn get_config(conn: &Connection, key: &str) -> Result<Option<String>> {
    use mini_orm::Table;
    use schema::AppConfig;

    // Type-safe SQL: "SELECT value FROM app_config WHERE key = ?1"
    let sql = format!(
        "SELECT {} FROM {} WHERE {}",
        AppConfig::value.col_name(),
        AppConfig::table_name(),
        AppConfig::key.eq_param(1).to_sql()
    );
    let mut stmt = conn.prepare(&sql)?;
    let val = stmt
        .query_row([key], |row| row.get::<_, String>(0))
        .optional()?;
    Ok(val)
}

pub fn set_config(conn: &Connection, key: &str, value: &str) -> Result<()> {
    use mini_orm::Table;
    use schema::AppConfig;

    // Type-safe upsert
    let sql = format!(
        "INSERT INTO {}({}, {}) VALUES(?1, ?2) \
         ON CONFLICT({}) DO UPDATE SET {} = excluded.{}",
        AppConfig::table_name(),
        AppConfig::key.col_name(),
        AppConfig::value.col_name(),
        AppConfig::key.col_name(),
        AppConfig::value.col_name(),
        AppConfig::value.col_name()
    );
    conn.execute(&sql, (key, value))?;
    Ok(())
}

// ============================================================================
// Diesel-based config helpers (cleaner DSL syntax)
// ============================================================================

use diesel::prelude::*;
use diesel::result::OptionalExtension as DieselOptionalExtension;

/// Diesel-based get_config - true DSL, no string formatting
pub fn get_config_diesel(
    conn: &mut diesel::SqliteConnection,
    key_param: &str,
) -> Result<Option<String>> {
    use diesel_schema::app_config::dsl::*;

    let result = app_config
        .filter(key.eq(key_param))
        .select(value)
        .first::<String>(conn)
        .optional() // This is diesel's optional from DieselOptionalExtension
        .map_err(|e| anyhow!("Diesel query failed: {}", e))?;

    Ok(result)
}

/// Diesel-based set_config - true DSL upsert
pub fn set_config_diesel(conn: &mut diesel::SqliteConnection, k: &str, v: &str) -> Result<()> {
    use diesel_schema::app_config::dsl::*;

    diesel::insert_into(app_config)
        .values((key.eq(k), value.eq(v)))
        .on_conflict(key)
        .do_update()
        .set(value.eq(v))
        .execute(conn)
        .map_err(|e| anyhow!("Diesel insert failed: {}", e))?;

    Ok(())
}

/// Helpers

fn hex_encode_upper(bytes: &[u8]) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let mut s = String::with_capacity(bytes.len() * 2);
    for &v in bytes {
        s.push(HEX[(v >> 4) as usize] as char);
        s.push(HEX[(v & 0x0F) as usize] as char);
    }
    s
}

#[cfg(test)]
mod tests;
